### ISSUE TITLE
opening mailto links does nothing

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#905] opened 2019-07-25 06:09 UTC
I click mailto links, choose to open with deltachat-desktop, the Delta Chat window is raised but nothing happens, it should open the chat with that contact and fill the text area with the data from the mailto link, if the contact doesn't exist, ask "do you want to chat with X?" before creating the chat.

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: v0.105.0-pre2
- Expected behavior: mailto links works as in other email clients
- Actual behavior: opening mailto link does nothing
- Steps to reproduce the problem: click a mailto link like mailto://someone@example.com?body=hello and try to open it with delta chat

**Comment by Simon-Laux** [comment] 2019-08-27 21:18
I have an Idea: **when the contact it should be sent at is already defined** it just shows a dialog where you can confirm the sent and edit the message.

What do think about this? Other option would be the remember choice like it should be on android.

**Comment by nicodh** [comment] 2019-10-25 21:31
I would not consider this a bug but a missing feature

**Comment by pabzm** [comment] 2020-01-06 13:19
I agree that this is not a bug but an enhancement. As we don't want to collect feature ideas in the issue tracker and no one is actively working on it, I'm closing it.

**Closed by pabzm** 2020-01-06 13:19 UTC
Labels: enhancement
