### ISSUE TITLE
"Add members" annoyingly forgets actually added members

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1964] opened 2020-11-21 08:25 UTC
Using pretty current master but this issue has been here for a long time: 

When you create a new group chat, then "add members" and use the searchbar to find individuals, then "check" the box for adding them, then continue to search, add another member .... and maybe add 7 members this way, then only the very last one will actually be added.  It doesn't accumulate my "clicking the checkboxes" of indivudal members but seems to forget it as soon as a new search or a new click or something comes.  I've ran into this at least 10 times and now decided to raise the issue, finally :)

**Comment by Simon-Laux** [comment] 2020-11-21 12:13
duplicate of #1939

**Closed by Simon-Laux** 2020-11-21 12:13 UTC
Labels: bug, duplicate
