### ISSUE TITLE
My messages don't show up on my other device (and there's no "copy messages to self" settings option)

### ISSUE THREAD

**Issue by rschr** [deltachat/deltachat-desktop#1405] opened 2020-01-30 09:52 UTC
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: 0.901.0
- Expected behavior: My chat messages show up on my other device (Android), too 
- Actual behavior: They don't

I have Delta Chat open on both a Linux netbook and an Android phone. Being in the same chat on both devices, when I send a message from the phone, it appears on the netbook, too. When I send something from the netbook, though, it doesn't appear on the phone. And there is no settings option "copy messages to self" (or similar; neither on Linux nor on Android), as was suggested in a welcome text to enable the behaviour I'm missing. Did I perhaps overlook something?

**Comment by Simon-Laux** [comment] 2020-01-30 12:36
duplicate of #1187; and that option will be available in the next release

**Closed** 2020-01-30 12:36 UTC
Labels: duplicate

**Comment by pabzm** [comment] 2020-01-30 13:44
@rschr Thank you for reaching out!

As @Simon-Laux correctly noted, that feature will be available in the next release of Delta Chat Desktop, which will probably be published within the next one or two weeks. If with that upcoming version your problem still exists, please re-open this issue!

**Comment by rschr** [comment] 2020-01-30 13:46
Excellent, thanks @pabzm @Simon-Laux !
