### ISSUE TITLE
Disappearing messages don't vanish: message list isn't updated

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#3233] opened 2023-05-21 19:04 UTC
- Operating System: Linux
- Delta Chat Version: 1.36.4
- Expected behavior: when a disappearing message expires in an opened chat, it vanishes.
- Actual behavior: the expired message only vanishes after switching to another chat and switching back again.
- Steps to reproduce the problem:
  - set the timer to 30 seconds
  - send a message
  - wait 31 seconds
  - see how the message isn't deleted
  - switch to another chat
  - switch back to the test chat
  - see how the message isn't there anymore

**Comment by Simon-Laux** [comment] 2023-05-22 13:12
Is there an event when messages get deleted by disappearing messages?

**Comment by r10s** [comment] 2023-05-23 09:07
i'd like to understand he impact of this bug better.

@Simon-Laux does `DC_EVENT_MSGS_CHANGED(chat_id, 0)` or `DC_EVENT_MSGS_CHANGED(0, 0)` (in core, `emit_msgs_changed()` and `emit_msgs_changed_without_ids()`) stopped working at all on desktop?

this pattern is used at many places to inform about "larger modifications"  and should triggering reload of eg. chatlist and message list. if this pattern is not supported, there will be many more bugs (any maybe even more in the future when by multi-device usage changes are triggered by core and not user)

so DC_EVENT_MSGS_CHANGED(chat_id, 0)` and `DC_EVENT_MSGS_CHANGED(0, 0)` really needs to work again, and this bug will already being fixed by that.

that said, refactoring the event system and adding additional "precise events" make sense in many ways, however, this is a longer ongoing thing and should be regarded as an _optimisation and not as a bugfix_. we're just not there that we can have "precise events" in all situations - and even then, it is unclear if there may be still cornercases left where such a "large event" are needed.

**Comment by r10s** [comment] 2023-05-23 09:19
/me deleted my previous post as it was to broad wrt not supporting of `DC_EVENT_MSGS_CHANGED(chat_id, 0)` or `DC_EVENT_MSGS_CHANGED(0, 0)`

but yes, i still see https://github.com/deltachat/deltachat-core-rust/issues/4415 as an (maybe then optional) enhancement as that should be fired also at other places wrt message deletion.

to fix the issue, maybe call `emit_msgs_changed_without_ids()` instead of the for-loop in `delete_expired_messages`? this would be the same behavior as for manual deletion and that seems to  work on all platforms.

**Comment by Simon-Laux** [comment] 2023-06-04 14:39
> to fix the issue, maybe call emit_msgs_changed_without_ids() instead of the for-loop in delete_expired_messages? this would be the same behavior as for manual deletion and that seems to work on all platforms.

that would fix this issue, just looked at the code to confirm.

**Comment by Simon-Laux** [comment] 2023-07-11 12:35
was already fixed by #3273, there is a special message deletion event now, but adding it to the message list might not be trivial so I skipped doing that for now, because the issue is already solved.

**Closed by Simon-Laux** 2023-07-11 12:35 UTC
Labels: bug, new-core
