### ISSUE TITLE
syntax error: r1.1.0 crashes at startup

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#1508] opened 2020-03-11 10:30 UTC
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: r1.1.0
- Expected behavior: starts as usual, shows a window
- Actual behavior: crashes with uncaught SyntaxError exception at JSON.parse
- Steps to reproduce the problem: 
  - stop the desktop client
  - install r1.1.0
  - start it in a terminal to get this traceback:

```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.setLogHandler (/opt/DeltaChat/resources/app.asar/tsc-dist/shared/logger.js:35:15)
    at Object.<anonymous> (/opt/DeltaChat/resources/app.asar/tsc-dist/main/index.js:21:8)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/opt/DeltaChat/resources/app.asar/index.js:5:1)
```

- Logs:

the logfile is empty.

**Comment by r10s** [comment] 2020-03-11 10:46
same on mac: 
<img width="532" alt="Screen Shot 2020-03-11 at 11 43 21" src="https://user-images.githubusercontent.com/9800740/76408823-db5c0180-638d-11ea-8814-b5e9f6910623.png">

**Comment by francwalter** [comment] 2020-03-11 10:48
Same on Windows 8.1 (Ent. 64-Bit) with DeltaChat 1.0 installed.
After install of 1.1 the above crash comes up:
![grafik](https://user-images.githubusercontent.com/927269/76409124-4279b600-638e-11ea-985d-9254d4116ed3.png)

**Comment by missytake** [comment] 2020-03-11 11:36
exit code 0 btw...

**Comment by r10s** [comment] 2020-03-11 12:40
similar reports in the forum https://support.delta.chat/t/deltachat-desktop-1-1-0-linux-did-not-start/880

**Comment by Simon-Laux** [comment] 2020-03-11 12:46
strange, I did not get that on a local build, maybe the build script didn't work properly and packed old files.

**Comment by Jikstra** [comment] 2020-03-11 12:52
Not reproducible on arch. @Simon-Laux please test releases on various platforms before uploading them.

**Comment by pabzm** [comment] 2020-03-11 12:56
On my Arch Linux https://download.delta.chat/desktop/r1.1.0/DeltaChat-1.1.0.AppImage does fail with the described error.

**Comment by Jikstra** [comment] 2020-03-11 13:13
So it seems like all electron builder builds fail. The AUR package isn't using electron builder and might work fine because of that.

**Comment by gerryfrancis** [comment] 2020-03-11 13:27
Same behavior on Windows 8.1 Pro.

**Comment by Simon-Laux** [comment] 2020-03-11 16:20
Thanks for your information. The bug was not in the release, but in the build script that actually used some files from the previous build because it was broken. I now fixed it and already it replaced the uploaded files. Please re-download and test again.

**Comment by gerryfrancis** [comment] 2020-03-11 16:54
@Simon-Laux It works now, many thanks for the fast fix! :+1:

**Comment by r10s** [comment] 2020-03-11 17:21
yip, i can also confirm that this works on mac now.

@Simon-Laux was there a pr or so to fix that? or was it just a think going wrong on your local machine? for the future, however, i would prefer to have new version number and a new file in any case. having two file names with different versions tend to cause confusion (eg. downloads may be cached etc.)

another thing: the about dialog reports using core v1.26.0 - so the versions seems not to fix the encrypt-to-ecc-issue, i will file a separate issue for that.

**Comment by Simon-Laux** [comment] 2020-03-11 19:13
> @Simon-Laux was there a pr or so to fix that? or was it just a think going wrong on your local machine? for the future, however, i would prefer to have new version number and a new file in any case. having two file names with different versions tend to cause confusion (eg. downloads may be cached etc.)

as I said the build was broken, it didn't build the actual version. so there was no change to the source-code as the error was in the local build script. I should have marked it as pre-release or draft in github, though.

**Closed by Simon-Laux** 2020-03-11 19:13 UTC
Labels: blocker, bug

**Comment by r10s** [comment] 2020-03-11 22:03
> I should have marked it as pre-release or draft in github, though.

at least on android or ios, we usually do not to that on the release track.

we usually release versions as _1.2.0_ and push them to the testing groups. we do not mark them as pre-release or so in the version number.

- if things work out, this _exact_ apk/ipc is pushed to the stores - changing the version number would require a rebuild and has some risk - as happens in this issue.

- if things go wrong, we do a _1.2.1_ and start over.

for releases that are not supposed to make it to the release track, of course, this is a different thing.
