### ISSUE TITLE
Setup file crashing on Windows 8.1 & 10

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1269] opened 2019-12-22 08:15 UTC
**- Platform (linux/mac/windows):**
Windows 8.1 Pro (x64).

**- Delta Chat Desktop Version:**
0.901.0-1.34.1.

**- Expected behavior:**
Setup starts and installs Delta Chat.

**- Actual behavior:**
Setup starts but fails to install Delta Chat.

**- Logs:**
From Windows Event Log (unfortunately in German):
Name der fehlerhaften Anwendung: DeltaChat Setup 0.901.0.exe, Version: 0.901.0.0, Zeitstempel: 0x5a6fed7c
Name des fehlerhaften Moduls: System.dll, Version: 0.0.0.0, Zeitstempel: 0x5a6fed15
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00001581
ID des fehlerhaften Prozesses: 0x20f8
Startzeit der fehlerhaften Anwendung: 0x01d5b89db8f3119f
Pfad der fehlerhaften Anwendung: C:\Users\PC_USER\Downloads\DeltaChat Setup 0.901.0.exe
Pfad des fehlerhaften Moduls: C:\Users\PC_USER\AppData\Local\Temp\nsd4150.tmp\System.dll
Berichtskennung: f7848027-2490-11ea-8357-5c514fe0a33e
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

**- Comments:**
"DeltaChat Setup 0.900.0.exe" executes successfully, the prior version has been uninstalled.

**Comment by gerryfrancis** [comment] 2019-12-22 08:31
To me it seems to be some race condition: I executed the same setup file multiple times and that worked. Running Delta Chat 0.901.0 now...

**Comment by Simon-Laux** [comment] 2019-12-22 13:01
We don't generate the setup file ourselves. It gets generated by electron builder.

**Comment by gerryfrancis** [comment] 2019-12-22 16:40
Well, I did nothing to make the setup file run successfully, I just executed it several times, like starting the engine of a car, and suddenly the setup process started showing the process bar. I guess further investigation is needed to find the cause. Should you need any information about my Windows system, please let me know, thanks.

**Comment by Jikstra** [comment] 2019-12-22 17:14
Did this happen too on Deltachat Setup 0.900,1.exe?

**Comment by gerryfrancis** [comment] 2019-12-22 17:23
@Jikstra Do you mean 0.900.1 or 0.900.0? I had the latter one installed without any problem. If you want me to do a comparison, just let me know where I can grab 0.900.1, thanks.

**Comment by Jikstra** [comment] 2019-12-22 17:35
Ah sorry, mean 0.900.0, so just the previous setup file.
https://github.com/deltachat/deltachat-desktop/releases/download/v0.900.0/DeltaChat.Setup.0.900.0.exe

**Comment by gerryfrancis** [comment] 2019-12-22 17:44
Never mind. I just ran multiple tests with 0.900.0 and 0.901.0 and both have the very same issue. So it seems I was lucky in my first attempt of installing 0.900.0 (before 0.901.0 was released).

See https://github.com/electron-userland/electron-builder/issues/2751 as well. (Note: The exception offset is always the same, 0x00001581, so this should be the same issue.)

**Comment by gerryfrancis** [comment] 2019-12-22 19:53
Windows 7 and 10 seem to be affected as well, though I cannot test on such systems.

[Electron Builder 20.6.0 (pre-release)](https://github.com/electron-userland/electron-builder/releases/tag/v20.6.0) addresses an identical bug: https://github.com/electron-userland/electron-builder/issues/2518

@Jikstra or @ another DC developer: Should the issue be solved with a higher version of Electron Builder, maybe you might give it a try, compile a new Delta Chat setup file with it and send it over to me for testing, because this failure is thrown statistically in three of four tries.

**Comment by Jikstra** [comment] 2019-12-24 17:15
@gerryfrancis we're using 21.2.0 so this should be fixed already

**Comment by gerryfrancis** [comment] 2019-12-24 21:24
@Jikstra The portable file works, but I have to enter my login credentials with every run, which is not so neat.

FYI: Inspired by this comment https://github.com/vladimiry/ElectronMail/issues/6#issuecomment-360614994 , I copied the setup file from the "Downloads" folder of my user profile to another location ("C:\test") to execute it from there for appx. five times, and I could not reproduce the issue. Then I ran the (original) downloaded file located in the "Downloads" folder again, which resulted in an "APPCRASH" right away. So, it seems that the path or working directory of/to the executable setup file has an influence.

Merry Christmas to the whole team, you are doing a fantastic job!

**Comment by gerryfrancis** [comment] 2019-12-24 22:25
Gosh, I think I just nailed it...

Pre-information: In my first post, I replaced the real name of my user profile to "PC_USER". My full name consists of six characters for the first, and seven for the last (sir) name, with a space character in between.

You might want to do the following test to reproduce the issue:

1. Create a new folder named "test" in the root of "C:".
2. Copy setup file "DeltaChat Setup 0.901.0.exe" to "C:\test".
3. Create a new Windows user named "TestUser" (eight characters).
4. Add Windows user "TestUser" to the "Administrators" group.
5. Log on with the newly created Windows user "TestUser". (This step creates a new Windows user profile automatically.)
6. Copy setup file "DeltaChat Setup 0.901.0.exe" from "C:\test" to "C:\Users\TestUser\Downloads".
7. Execute setup file from "C:\Users\TestUser\Downloads", and install/uninstall Delta Chat for at least five times (if you can).

Result: No issues.

8. Log off Windows user "TestUser".
9. Delete the user profile of Windows user "TestUser".
10. Rename Windows user "TestUser" to "Testtest Useruser".
11. Log on Windows user "Testtest Useruser". (This step creates a new Windows user profile automatically.)
12. Copy setup file "DeltaChat Setup 0.901.0.exe" from "C:\test" to "C:\Users\Testtest Useruser\Downloads".
13. Execute setup file from "C:\Users\Testtest Useruser\Downloads", and install/uninstall Delta Chat for at least five times (if you can).

Result: At least one "APPCRASH" occurs. (I performed three tries, and all of them failed consistently.)

My conclusion: Either the length of the full path name or a space character inside can be a huge problem for the installer.

**Comment by gerryfrancis** [comment] 2019-12-24 22:27
Sorry, I accidentally closed the issue by pressing the wrong button...

**Comment by gerryfrancis** [comment] 2019-12-24 23:12
The issue most likely will not occur with Windows 10 under Microsoft user accounts, because usually the first five characters of the mail address are applied to the user directory name (e.g.: A Microsoft user account "firstname.sirname@example.org" will have the profile path "C:\Users\first\", considering that "C:" is the Windows OS volume.).

**Comment by gerryfrancis** [comment] 2020-02-03 06:52
Still an issue in version 0.999.1.

**Comment by Jikstra** [comment] 2020-02-06 06:41
We didn't update electron builder in 0.999.1 but shortly after. I want to trigger some preview builds including a recent electron builder to see if it works for you. Probably tomorrow or the next days.

**Comment by gerryfrancis** [comment] 2020-02-26 16:48
Sorry, it is still an issue in version 1.0.0:

**- Logs:**
Name der fehlerhaften Anwendung: DeltaChat-Setup-v1.0.0.exe, Version: 1.0.0.0, Zeitstempel: 0x5c157f86
Name des fehlerhaften Moduls: System.dll, Version: 0.0.0.0, Zeitstempel: 0x5c157efa
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00001581
ID des fehlerhaften Prozesses: 0x29d0
Startzeit der fehlerhaften Anwendung: 0x01d5ecc3cd832dfa
Pfad der fehlerhaften Anwendung: C:\Users\PC_USER\Downloads\DeltaChat-Setup-v1.0.0.exe
Pfad des fehlerhaften Moduls: C:\Users\PC_USER\AppData\Local\Temp\nsfFADE.tmp\System.dll
Berichtskennung: 0bf48b85-58b7-11ea-8364-d4c9eff87512
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

Looks like it has something to do with this: https://github.com/deltachat/deltachat-desktop/issues/1269#issuecomment-568807407

**Comment by gerryfrancis** [comment] 2020-03-11 13:23
Still an issue in version 1.1.0:

Name der fehlerhaften Anwendung: DeltaChat Setup 1.1.0.exe, Version: 1.1.0.0, Zeitstempel: 0x5c157f86
Name des fehlerhaften Moduls: System.dll, Version: 0.0.0.0, Zeitstempel: 0x5c157efa
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00001581
ID des fehlerhaften Prozesses: 0x60
Startzeit der fehlerhaften Anwendung: 0x01d5f7a77e80a77e
Pfad der fehlerhaften Anwendung: C:\Users\PC_USER\Downloads\DeltaChat Setup 1.1.0.exe
Pfad des fehlerhaften Moduls: C:\Users\PC_USER\AppData\Local\Temp\nszF166.tmp\System.dll
Berichtskennung: be2dd295-639a-11ea-8368-d4c9eff87512
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by Michael-Yongshi** [comment] 2020-03-26 20:30
It seams like i have the exact same issue on windows 10.
Both setup 1.1.0, 1.0.0 and 0.999.1 and 0.901 fails.
However 0.900 WORKS!

**Comment by Jikstra** [comment] 2020-03-28 18:25
@gerryfrancis you could workaround this bug with a different username? @Michael-Yongshi can you try the same? Not sure and hard to reproduce, but I would like to create new win10 users with the same usernames as you have, maybe I can then reproduce it?

**Comment by Michael-Yongshi** [comment] 2020-03-29 08:01
So i created 2 new local accounts with 1 called 'testing' and one called exactly the same as my microsoft account with a lot of spaces (i could dm that to you if you would like, for privacy reasons i will not put it here). Both went fine, so it must be the fact that it is a microsoft account which is faulty.

I did notice that the local accounts name is exactly the name of the folder under c/users and with the microsoft account its not (first 5 letters of email). Maybe thats the source of the issue?

**Comment by gerryfrancis** [comment] 2020-03-30 21:09
@Jikstra The user name should not make a difference. However, it seems that the name of the user profile matters. (See my explanation in https://github.com/deltachat/deltachat-desktop/issues/1269#issuecomment-568807407 .)
@Michael-Yongshi I have no Microsoft account, so I do not think that this has something to do with the issue.

**Comment by Michael-Yongshi** [comment] 2020-03-31 07:26
@gerryfrancis Well if microsoft account doesnt matter than it must be the path that is different that is the source of the issue. As I created a local account with exactly the same user profile name and there it works.

**Comment by gerryfrancis** [comment] 2020-03-31 08:25
@Michael-Yongshi Yes, that would match with my findings. (See https://github.com/deltachat/deltachat-desktop/issues/1269#issuecomment-568807407 .)

**Comment by Michael-Yongshi** [comment] 2020-04-22 06:17
Just uninstalled delta-chat 9.000 and tried to install 1.1.0 and worked perfectly. But i dont think it uninstalled everything, as i didnt have to import anything, it immediately opened in my chats. 

so updating from an older version to a newer one does work, so maybe the issue is with the data files...

**Comment by gerryfrancis** [comment] 2020-04-22 09:11
> But i dont think it uninstalled everything, as i didnt have to import anything, it immediately opened in my chats.

@Michael-Yongshi I guess that is an intended behavior. The database of Delta Chat resides in the respective user profile of the operating system and will not be uninstalled. I do not think that it is a good idea to remove the chat data during the uninstall process.

**Comment by gerryfrancis** [comment] 2020-05-05 20:13
Still an issue in version 1.3.0.

**Comment by Jikstra** [comment] 2020-05-05 22:18
Thanks for keeping an eye on those issues and updating us! I'm currently busy with fixing mac specific bugs, but will switch to windows again in some time to squash bugs there :)

**Comment by gerryfrancis** [comment] 2020-05-06 05:12
@Jikstra No worries here, just take your time. :)

**Comment by Michael-Yongshi** [comment] 2020-05-06 06:10
Maybe add the workaround to the readme in the meantime?
(install 0.900 first and than update to newer version)

**Comment by gerryfrancis** [comment] 2020-05-06 08:19
@Michael-Yongshi I would not recommend installing version 0.900.1, it is quite old. For me it works with a Windows user profile that has a shorter name, but of course this is just a workaround.

**Comment by Michael-Yongshi** [comment] 2020-05-06 12:25
> 
> 
> @Michael-Yongshi I would not recommend installing version 0.900.1 and update afterwards. For me the installation of version 1.3.0 works when using a Windows user profile that has a shorter name. But of course this is just a workaround.

Well the whole idea is that if you are using a windows account you can't just change the account name, right ;)

**Comment by gerryfrancis** [comment] 2020-05-06 14:00
@Michael-Yongshi AFAIK, only the name of the user can be changed, but not the name of the respective profile (located in "C:\Users"), unless there exist special tools to do this. (I do not know any of such.)

**Comment by Michael-Yongshi** [comment] 2020-05-06 15:34
Sure technically you can, but not only for this app or only on one pc, is what I really meant.
The profile is indeed copied after the first 5 letters or so of your email, so yeah can't change that.

**Comment by gerryfrancis** [comment] 2020-06-27 13:23
Still an issue in version 1.4.2.

**Comment by gerryfrancis** [comment] 2020-06-27 13:38
Ah! I tried multiple times to experience something I have not recognized before: The setup dialog window is not always in foreground. Sometimes it is minimized, sometimes not.

Now I think some function, maybe focus, wants to call the setup dialog window which is not available, yet, crashing the process as a whole. Probably it helps to withdraw focusing (or hiding) the window.

**Comment by gerryfrancis** [comment] 2020-07-16 09:14
Still an issue in version 1.10.0.

**Comment by gerryfrancis** [comment] 2020-07-31 22:17
Still an issue in version 1.12.0.

**Comment by gerryfrancis** [comment] 2020-08-16 12:45
Still an issue in version 1.13.0 RC1.

**Comment by Simon-Laux** [comment] 2020-10-13 17:13
what should we do about this? should create an issue on the electron builder issues page?

**Comment by gerryfrancis** [comment] 2020-10-13 17:29
@Simon-Laux Thanks for the reminder, I will perform further tests with the current Desktop setup within 24 hours and report back.

**Comment by gerryfrancis** [comment] 2020-10-13 21:55
@Simon-Laux The issue is not resolved:

Name der fehlerhaften Anwendung: DeltaChat Setup 1.13.1.exe, Version: 1.13.1.0, Zeitstempel: 0x5c157f86
Name des fehlerhaften Moduls: System.dll, Version: 0.0.0.0, Zeitstempel: 0x5c157efa
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00001581
ID des fehlerhaften Prozesses: 0x4b50
Startzeit der fehlerhaften Anwendung: 0x01d6a1aa78934ce8
Pfad der fehlerhaften Anwendung: C:\Users\PC_USER\Downloads\DeltaChat Setup 1.13.1.exe
Pfad des fehlerhaften Moduls: C:\Users\PC_USER\AppData\Local\Temp\nsgCBB1.tmp\System.dll
Berichtskennung: b91bdbcb-0d9d-11eb-83a1-d4c9eff87512
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

I have added the information that the setup file also crashes on Windows 10 systems, as reported from @Michael-Yongshi . Please also read my https://github.com/deltachat/deltachat-desktop/issues/1269#issuecomment-568807407 above. Thanks!

**Comment by xiajingren** [comment] 2020-12-16 03:00
hi. Has this problem been solved? I have the same problem

**Comment by Jikstra** [comment] 2020-12-16 15:42
> hi. Has this problem been solved? I have the same problem

Can you try out the latest version and reply back if it still occurs? I couldn't reproduce this yet on any windows 10 machine.

**Comment by xiajingren** [comment] 2020-12-17 02:28
> > hi. Has this problem been solved? I have the same problem
> 
> Can you try out the latest version and reply back if it still occurs? I couldn't reproduce this yet on any windows 10 machine.

hi. thank you for your reply. In fact, sometimes my program installed on windows 7 has a similar crash problem. How do you solve this problem? Can you share it?thanks!

I also used electron-builder

**Comment by Jikstra** [comment] 2020-12-17 03:06
@xiajingren we probably didn't fix it yet, let's ask @gerryfrancis about this as he reproduced it most often i think?

**Comment by xiajingren** [comment] 2020-12-17 03:16
@Jikstra thank you very much. my situation is the same as this issue: https://github.com/electron-userland/electron-builder/issues/3545
this problem has bothered me for a long time.i don't know why.

**Comment by gerryfrancis** [comment] 2021-01-14 08:38
@Jikstra Sorry for the late reply, I was not able to test earlier. Yes, unfortunately the issue still exists, I cannot install version 1.14.1 right now, same behavior...

**Comment by gerryfrancis** [comment] 2021-02-14 17:30
Still an issue in version 1.15.1.

**Comment by gerryfrancis** [comment] 2021-03-19 08:47
Still an issue in version 1.15.3.

**Comment by gerryfrancis** [comment] 2021-03-30 15:36
Still an issue in version 1.15.5.

**Comment by gerryfrancis** [comment] 2021-05-29 23:11
Still an issue in version 1.20.1.

**Comment by gerryfrancis** [comment] 2021-06-17 12:30
Still an issue in version 1.20.2.

**Comment by gerryfrancis** [comment] 2021-07-03 16:54
Still an issue in version 1.20.3.

**Comment by Simon-Laux** [comment] 2021-07-06 14:49
https://github.com/electron-userland/electron-builder/issues/5119 might help debugging this, but changing stuff in cache directories is not a clean solution in my eyes.

Also there is the option to disable the oneclick installer and allow the user to choose where to install DC to: https://www.electron.build/configuration/nsis

**Comment by Simon-Laux** [comment] 2021-07-08 22:04
somebody could look in the NSIS issue tracker if they find our issue there, if someone has time to do it currently: https://sourceforge.net/p/nsis/bugs/

**Comment by gerryfrancis** [comment] 2021-09-11 16:04
Still an issue in version 1.21.0.

**Comment by gerryfrancis** [comment] 2023-04-17 13:33
Still an issue in version 1.36.2.

**Comment by farooqkz** [comment] 2023-07-31 11:25
Might be related: https://github.com/electron-userland/electron-builder/issues/6427

**Comment by gerryfrancis** [comment] 2023-07-31 12:15
> Might be related: https://github.com/electron-userland/electron-builder/issues/6427

@farooqkz Why do you think the issue might be related? That crash occurs at the end of the Installation process, while our crash happens immediately after the launch of the setup program.

**Comment by Simon-Laux** [comment] 2024-06-09 17:21
does this still happen with https://download.delta.chat/desktop/v1.45.4/ ?

Also we gave up on the certificate / windows signing for now as it is too annoying & expensive to get a signing key, maybe  we'll pick it up in the future again, but you can already get deltachat over the microsoft store, so might not be needed (especially as you still get the annoying warnings, even when you have a certificate).

**Comment by nicodh** [comment] 2024-07-30 09:33
@gerryfrancis sorry for repeating the same question since years now... :-(
But can you please report if the crash still occurs with current version?

**Comment by Simon-Laux** [comment] 2024-07-31 21:15
Lasted status that I know:
We suspected this is an interaction between an anti virus software and the nsis installer that is generated by electron builder.
We hoped signing the executable would fix it, but we didn't manage to sign it correctly and/it didn't worked.
After ssl.com stoped giving out certificate key and tried to charge extra for signing with their e-signer (uploading to their site to sign) instead, we gave up for now on the certificated (that is way too expensive anyway, like 200 bucks per year).
Maybe it's possible to change the NSIS script/installer to not interact and to not be disturbed by the antivirus software, but it's so deep inside of electron-builder that it's likely easier to make the installer from scratch. (or with electron forge, which is more hands-on/low-level and the officially endorsed (by electron) way now anyway)

Anyways after many years nobody managed to fix it, so I'll close it as won't fix.
Let's hope that the installer generated by tauri (when I completed the delta tauri project) works better in that regard.

**Closed by Simon-Laux** 2024-07-31 21:15 UTC
Labels: bug, OS: Windows

**Comment by gerryfrancis** [comment] 2024-08-01 11:16
I think we should distinguish two issues here:

1. Codesign certificate to verify code genuinity.
My conviction is that _any_ distributed code shall be signed by its developer to e.g. prevent and avoid a setup file to become modified by anyone else. Of course, no one can guarantee that a place/store to download such files will never be hacked one day, as attackers become more and more creative. If e.g. they modified setup files, the users who were trying to execute them would usually be warned by the operating system that the signature of these files was no longer valid (broken) and, therefore, not genuine anymore.
2. The crash itself (whose real cause still seems to be unknown).
I will try to collect more information about that NSIS installer crash. Issues like [this one](https://github.com/electron-userland/electron-builder/issues/7921) have not been closed, yet, so we are not the only ones left in the dark.
