### ISSUE TITLE
Chat scrolls not to completely to bottom if pictures are present

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#477] opened 2018-12-23 20:47 UTC
Probably its when pictures get loaded and grow in height after scrolling to the bottom.

A possible solution could be to use a bigger "skeleton" image placeholder that shrinks to the right size after the image is loaded.

**Comment by ralphtheninja** [comment] 2018-12-23 21:03
I've also noticed this.

**Comment by nicodh** [comment] 2019-06-15 10:52
Can't reproduce this. Maybe it's obsolete?

**Comment by nicodh** [comment] 2019-07-04 22:25
@ralphtheninja @Simon-Laux 
if you also can't reproduce this anymore I will close the issue

**Comment by ralphtheninja** [comment] 2019-07-04 23:43
I can still reproduce.

**Closed** 2019-12-08 22:27 UTC
Labels: bug
