### ISSUE TITLE
Animated GIFs no longer play when sent

### ISSUE THREAD

**Issue by binarydad** [deltachat/deltachat-desktop#3570] opened 2023-11-27 20:10 UTC
Previously, I was able to copy/paste an animated GIF and not only did it play in the text box, but also (of course) in the chat history. It also worked for attaching a GIF image. Now, while the animation plays when pasting the image or attaching an image, when sent, just a static image is sent. I can get it to work when I attach as a "File" instead of an "Image". 

I imagine this is due to the new image compression happening in this new version? Can GIF images be ignored when compressing before being sent?

- Operating System (Linux/Mac/Windows/iOS/Android): Windows
- Delta Chat Version: 1.42.1
- Expected behavior: GIF images that are sent play animation in the chat history/window
- Actual behavior: Previous behavior, where pasted animated GIF images and attached "Images" are not compressed and sent as-is
- Steps to reproduce the problem: Find an animated GIF (say, giphy.com), copy and paste into the chat text box (note that it plays once pasted), and hit send. The image is no longer animated. The same behavior is seen when attaching an "Image". 
- Screenshots: *none*
- Logs: *none*

**Comment by Simon-Laux** [comment] 2023-11-28 20:38
> Find an animated GIF (say, giphy.com), copy and paste into the chat text box (note that it plays once pasted)

how do you copy it from giphy? when I try to copy it I get the current frame as png

**Comment by Simon-Laux** [comment] 2023-11-28 21:09
downloading the webp file and dropping it into deltachat desktop works (still animated), but if I copy from firefox or from chrome I get the image only as png, log output:

```
 Clipboard available formats: [ 'image/png', 'text/html' ]
```
maybe it is somewhere inside of the html as base64, I need to check that, but other than that there is not much we can do about it, maybe it's a bug in chrome or in electron? do you know any apps where this works?

**Comment by Simon-Laux** [comment] 2023-11-28 21:36
So impossible to fix I'd say unless we want to write native code that extracts the clipboard contents, but even then IDK if browsers even copy to clipboard correctly or already convert to png while copying?

**Comment by binarydad** [comment] 2023-11-28 21:39
I'll try and swing back on this tonight but I know this used to work, at least for a short while. I was able to copy GIFs (right-click, copy image) and paste into the chat box. Not only did it play in the chat box, but also in the message history once sent. It was actually really convenient. 

This was on Firefox. I have not tried Chrome/Edge.

Even Win + . on Windows 11 didn't work as nicely.

**Comment by Simon-Laux** [comment] 2023-11-29 21:10
I suspect the electron upgrade more than the image compression because drag and dropping and attaching the image files still works perfectly for me. (though webp is not selectable in the image attachment chooser, maybe sth. for a dedicated issue?)

**Comment by farooqkz** [comment] 2023-12-06 11:56
I just tested with two GIFs:

https://tenor.com/view/catjam-cat-music-jam-vibing-gif-20520051
https://giphy.com/gifs/starwars-oQkEpeve8GcCSh9QcH

I've pasted them in Telegram's saved messages and DC's. The results were the same. The GIF is not animated anymore. So I guess the issue is invalid?

**Comment by Simon-Laux** [comment] 2023-12-06 17:25
I think it's also a bug of the browsers, looks like sth we can not really solve, or only partially solve that it only works with some browsers (firefox in this case).
I'll close it and put it to project resurrection, as there is no real actionable item for us right now.

**Closed by Simon-Laux** 2023-12-06 17:25 UTC
Labels: bug
