### ISSUE TITLE
Add some sort of spinner with feedback information

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#49] opened 2018-09-18 19:54 UTC
Currently it can take quite some time to generate keys etc. Using a spinner and providing some feedback text from `DC_EVENT_INFO` (plus other events?) will let the user know something is going on.

**Comment by r10s** [comment] 2018-09-19 09:53
related: https://github.com/deltachat/deltachat-ios/issues/11#issuecomment-422713154

maybe we can use data2 of [DC_EVENT_CONFIGURE_PROGRESS](https://deltachat.github.io/api/group__DC__EVENT.html#gae047f9361d57c42d82a794324f5b9fd6) to add some text to what is happening.

**Comment by karissa** [comment] 2018-09-19 17:58
@ralphtheninja there was a spinner implemented, but right now the key transfer is blocking the thread. See https://github.com/deltachat/deltachat-node/pull/111

**Comment by karissa** [comment] 2018-09-19 17:59
duplicate of https://github.com/deltachat/deltachat-desktop/issues/33

**Closed** 2018-09-19 20:09 UTC
Labels: enhancement
