### ISSUE TITLE
Select a message group

### ISSUE THREAD

**Issue by JackJeisly** [deltachat/deltachat-desktop#3347] opened 2023-08-06 09:53 UTC
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.39.0 AppImage
- Expected behavior: Really missing is group selection of messages by Ctrl+Click and Shift+Click for them deletion or send to "saved messages".
- Actual behavior: I can select one message only
- Steps to reproduce the problem: Does not effect  by Ctrl+Click and Shift+Click
- Screenshots:
- Logs:

**Comment by Simon-Laux** [comment] 2023-08-06 19:48
technically this is a duplicate of #2892
I agree that this feature would be nice to have.

**Closed by Simon-Laux** 2023-08-06 19:48 UTC
Labels: duplicate, enhancement
