### ISSUE TITLE
Change contact name on desktop app

### ISSUE THREAD

**Issue by zikalify** [deltachat/deltachat-desktop#1518] opened 2020-03-18 10:38 UTC
- Platform (linux/mac/windows): Linux Flatpak app
- Delta Chat Desktop Version: v1.27.0
- Expected behavior: Be able to change a contact's name
- Actual behavior: No option to change contact's name
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by gerryfrancis** [comment] 2020-03-18 13:38
@zikalify If your issue is a duplicate of https://github.com/deltachat/deltachat-desktop/issues/1502 , please close here, thank you.

**Closed** 2020-03-22 19:49 UTC
Labels: duplicate
