### ISSUE TITLE
line wrapping missing in device-chat's "signature text"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3555] opened 2023-11-21 19:52 UTC
the "signature text" of the device-chat lacks line wrapping (i did not tested other signatures, maybe they have the same issue)

<img width="542" alt="Screenshot 2023-11-21 at 20 51 39" src="https://github.com/deltachat/deltachat-desktop/assets/9800740/601079f7-ec05-4426-83b1-91f3bb65eaea">

**Comment by Simon-Laux** [comment] 2023-11-21 20:25
duplicate of #3515 was fixed by https://github.com/deltachat/deltachat-desktop/pull/3517

**Closed** 2023-11-21 20:35 UTC
Labels: duplicate

**Comment by r10s** [comment] 2023-11-21 20:37
upps, wrong taps,  on mobile everything is close together.

however, great that it is already fixed, thanks for the links - and sorry for the noise
