### ISSUE TITLE
kernel trap while running via flatpak

### ISSUE THREAD

**Issue by DynamicOperationsArchitect** [deltachat/deltachat-desktop#3607] opened 2023-12-30 20:48 UTC
This affects the current version on Flathub (Delta Chat Desktop v1.42.2).

Tested with flatpak 1.14.4 under Debian 12.4 and openSUSE 15.5. 

From time to time Delta Chat Desktop crashes with the following (or similar) error while running via flatpak:

`kernel: [ 5500.105607][T18236] traps: deltachat-deskt[18236] trap int3 ip:558a98e694ac sp:7ffe14b7f610 error:0 in deltachat-desktop[558a989ed000+79c9000]`

**Comment by DynamicOperationsArchitect** [comment] 2023-12-31 13:55
Might be a duplicate of https://github.com/deltachat/deltachat-desktop/issues/3590. I can reproduce the kernel trap when I try to open unread messages.

**Comment by Simon-Laux** [comment] 2024-01-10 00:09
let's treat it as duplicate of #3590, which has the same reproduction steps and looks similar in terms of error message

**Closed by Simon-Laux** 2024-01-10 00:09 UTC
Labels: bug, flatpak
