### ISSUE TITLE
text "No messages" flashes up shortly on sending

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2131] opened 2021-02-17 09:47 UTC
when sending a message to any chat, directly after hitting the send button, in the chatlist appears the text "No messages" for a little moment. After that the chat is shown correctly.

not an urgent bug, of course, however, still a bit annoying and creating useless noise and flickering on the screen. also a redraw seems to be wasted.

therefore, i think a closer look is reasonable, maybe it is an easy thing.

if that is not easily fixable because of $reasons or has the risk of introducing more bugs, maybe it is fine to leave it as is and to close the issue.

**Comment by Simon-Laux** [comment] 2021-02-17 14:00
likely a core thing, it come up after clearing a draft.

**Comment by gerryfrancis** [comment] 2021-02-17 21:05
I have experienced the issue while typing a message. To me it appears like the app waits for a typing break to save the draft. Until then, the message "No messages" appears.

**Comment by Simon-Laux** [comment] 2021-03-17 15:34
I believe the problem is that core sends a `DC_EVENT_MSGS_CHANGED` event, but the message id is not the id of the draft but always 0. so it takes the old id of the draft message that is already deleted. so the message is not found and it displays "no messages".

**Comment by Simon-Laux** [comment] 2022-03-12 19:36
was somewhere fixed in the meantime, as I can not reproduce it anymore.

**Closed by Simon-Laux** 2022-03-12 19:36 UTC
Labels: bug

**Comment by r10s** [comment] 2022-03-14 12:10
also autofix :)
