### ISSUE TITLE
You don't see a user's reaction if they have a long domain name

### ISSUE THREAD

**Issue by Gh0stz0x** [deltachat/deltachat-desktop#3822] opened 2024-05-15 19:48 UTC
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.44.1
- Expected behavior: when I click on one or more given reactions, I would like to see what kind of reaction a user has given.
- Actual behavior: When a user has a long domain name, the given reaction remains hidden.
- Steps to reproduce the problem: To reproduce the problem you need to have an account with a long domain name, then you need to click on a reaction given by one or more users and the list of users who reacted will appear,  the reaction given for each user will not appear in the list.
- Screenshots:
![Schermata del 2024-05-15 21-37-34](https://github.com/deltachat/deltachat-desktop/assets/168986411/d0c53bfe-de9f-4209-912e-0e697736fa76)
- Logs:

**Comment by maxphilippov** [comment] 2024-08-03 11:27
Can't reproduce on main (git: 3265230700ea5b354b0e86d2c3e5560ebf92a892)
![image](https://github.com/user-attachments/assets/e6613cd9-a2e0-4ab0-aeaf-df7e94415275)

**Comment by maxphilippov** [comment] 2024-09-11 16:33
I will close this one for now, if the issues persist, please, feel free to reopen.

**Closed by maxphilippov** 2024-09-11 16:33 UTC
Labels: bug
