### ISSUE TITLE
order of messages with images not according to Date: header

### ISSUE THREAD

**Issue by jdegraef** [deltachat/deltachat-desktop#1276] opened 2019-12-27 16:20 UTC
- Platform windows 
- Delta Chat Desktop Version: 0.900.0-preview
- Expected behavior:
display messages according to Date: header in email
- Actual behavior:
message with images are shown in order they are sent/received
- Steps to reproduce the problem:
testcase: several images each sent with Date: header one hour further in the past.
- Screenshots:
![image](https://user-images.githubusercontent.com/12233640/71524280-21e0aa80-28cd-11ea-8ba4-f0ab417d48e7.png)
![image](https://user-images.githubusercontent.com/12233640/71524291-2d33d600-28cd-11ea-97db-b596b5ac4964.png)
![image](https://user-images.githubusercontent.com/12233640/71524296-3755d480-28cd-11ea-959d-d490a3b8526d.png)

**Comment by jdegraef** [comment] 2019-12-27 16:26
FYI: behaviour is the same on android. 
txt only message are ordered correctly, the msgs with images are added at the end ('now') of the chat.

**Comment by r10s** [comment] 2020-01-07 20:07
in general, this is by design currently. messages are ordered by incoming date, see https://support.delta.chat/t/order-of-messages/698 for further information and a discussion on that.

i do not think, this has really to do with image-only or not, esp. if the behavior is regarded as the same as on android.

closing this here, there is no actionable item for deltachat-desktop.

**Closed by r10s** 2020-01-07 20:07 UTC
