### ISSUE TITLE
enlarging group-image broken

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1927] opened 2020-10-12 20:00 UTC
enlarging the group-image as of https://github.com/deltachat/deltachat-desktop/issues/1601 is broken.

enlarging user-images is still working.

tested on mac 1.13.1

**Comment by Simon-Laux** [comment] 2020-10-12 22:25
duplicate of https://github.com/deltachat/deltachat-desktop/issues/1924

**Closed by Simon-Laux** 2020-10-12 22:25 UTC
Labels: bug, duplicate
