### ISSUE TITLE
no context menu on input fields

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2047] opened 2021-01-12 11:20 UTC
normally, a right-click in an input field shows a system-context-menu with cut/copy/paste and maybe other system-special things (spell correction etc).

currently, this system-context-menu does not appear - but also, no replacement that may be done by chrome appears.

not sure, if the system-context-menu is doable, however, having a menu with at least "paste" is expected in many workflows. i just checked signal, who are also using electron afaik, and there is a context menu.

maybe there is just a return value from some event handler wrong? so that passing the click to the default handler is skipped?

(tested on macos with delta 1.14.1)

**Comment by Simon-Laux** [comment] 2021-01-12 11:43
> currently, this system-context-menu does not appear

electron doesn't have one.

looks like maybe electron has a way to use the system menu: https://www.electronjs.org/docs/tutorial/spellchecker, so we could  have an option that it used instead of our implementation if available... (we can think about that after upgrading electron, but that's a sidequest this only affects how the context menu will look, probably)

What we need is an catch-all on contextmenu that triggers on input fields and only triggers if the event wasn't handled before. I would appreciate if we find a way for that without calling `event.preventDefault()` and `event.stopPropagation`.

related:
https://github.com/deltachat/deltachat-desktop/issues/1997 (this issue #2947 is halfway duplicate of this one, this issue talks about all input fields and the other one only about the message input field. I'll close #1997 in favor of this one because it is broader defined)
https://support.delta.chat/t/help-testing-the-upcomming-1-14-x-release/1267/2

**Closed** 2021-02-05 10:33 UTC
Labels: bug, enhancement
