### ISSUE TITLE
Can not open Key File

### ISSUE THREAD

**Issue by narc-Ontakac2** [deltachat/deltachat-desktop#2395] opened 2021-10-17 08:28 UTC
- Operating System (Linux/Mac/Windows/iOS/Android): Debian bullseye amd64
- Delta Chat Version: deltachat-desktop 1.22.2 
- Expected behavior: Key file can be selected
- Actual behavior: Key file is greyed out
- Steps to reproduce the problem: 
1. Export a key from an android delta chat
2. move it to the linux system
3. Try to open it for import with deltachat-desktop

![grafik](https://user-images.githubusercontent.com/42581924/137618389-2f69691f-3d19-4d0e-8aba-def3ff2e7802.png)

~/Downloads$ ls -l private-key-default.asc 
-rw------- 1 jo jo 5069 17. Okt 10:03 private-key-default.asc
`

**Comment by farooqkz** [comment] 2023-07-27 13:26
I am also using i3 but I am using XFCE and have just replaced the WM with i3. And I can't reproduce this.

**Comment by narc-Ontakac2** [comment] 2023-07-27 17:46
As far as I understand what I have written (remembering is somewhat difficult after two years) this is a usability issue. It is not obvious you have to select the surrounding folder. The key file can not be selected.

**Comment by Simon-Laux** [comment] 2023-09-28 15:03
duplicate of #1863

I will fix it there

**Closed by Simon-Laux** 2023-09-28 15:03 UTC
Labels: bug
