### ISSUE TITLE
When read receipt arrives, message is not marked with double-tick immediately.

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1306] opened 2020-01-06 17:08 UTC
Also when read receipt arrives, message is not marked with double-tick immediately. I have to switch to another chat and back to see it.

_Originally posted by @link2xt in https://github.com/deltachat/deltachat-desktop/issues/1293#issuecomment-571075219_

**Comment by gerryfrancis** [comment] 2020-02-03 21:41
Still an issue in version 0.999.1.

**Comment by gerryfrancis** [comment] 2020-02-03 21:50
FYI: The double-tick is shown in the list of contacts (on the left side of the window) underneath the respective contact name, but not in the message blob (on the right side of the window) itself, and that message already has the status "Read". So I guess that might be a minor issue.

**Comment by Jikstra** [comment] 2020-02-04 02:44
Duplicate of https://github.com/deltachat/deltachat-desktop/issues/1293

**Comment by gerryfrancis** [comment] 2020-02-04 06:46
I do not believe that this is a duplicate of https://github.com/deltachat/deltachat-desktop/issues/1293 , because the message _is_ read, just the double-tick within the blob is missing. The other issue is about messages not marked as read at all.

Regarding _this_ issue, this is what has been recorded when the double-tick is missing:

`"2020-02-04T06:31:18.377Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:221:17),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(9) src\\job.rs:641: could not interrupt idle: try_lock failed because the operation would block"`

**Comment by pabzm** [comment] 2020-02-04 08:44
This is indeed a separate issue.

**Closed** 2020-02-16 13:21 UTC
Labels: bug
