### ISSUE TITLE
Long attachment name allows sideways scrolling in the message list

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2462] opened 2021-12-14 13:31 UTC
- Expected behaviour: no sideways scrolling under any circumstances in the message list
- Actual behaviour: messages with long attachment name break this rule
- Possible solution: truncate the attachment name if the message gets to long (possibly with css if possible.

**Comment by naomiceron** [comment] 2021-12-15 21:19
Hello! I would like to give this issue a try, could you assign it to me? :)

**Comment by Jikstra** [comment] 2021-12-16 02:10
@naomiceron claro, give it a try :)

**Comment by naomiceron** [comment] 2021-12-16 04:27
I tried to replicate this bug using MacOS 12.0.1, both in the actual DeltaChat app and running it in Electron, tried long links and names of files but I haven't seen sideways scrolling, could you give me more information on how to replicate it, please? 
<img width="1106" alt="Screen Shot 2021-12-15 at 21 24 08" src="https://user-images.githubusercontent.com/58761246/146307855-8070aa1c-45fd-4b59-b573-9e43db9d269f.png">

**Comment by Jikstra** [comment] 2021-12-16 11:07
![Screenshot_20211216_120506](https://user-images.githubusercontent.com/34889164/146360453-39ef2e15-10b3-4212-8a86-79ee2ea92589.png)
![Screenshot_20211216_120620](https://user-images.githubusercontent.com/34889164/146360636-a15baa42-3937-4a42-a85c-6306b613b875.png)

It's reproducable with links inside quotes/replies and small window sizes. It happens both for messages you send out and you receive. I guess the problem is that we dont have a break all for links, maybe we should also shorten the links and add some "..." somewhere.

**Comment by Simon-Laux** [comment] 2021-12-16 18:19
It's about names of attachments, like give a file a long name and send it with deltachat

**Closed** 2022-01-10 14:19 UTC
Labels: bug, good first issue, ui/ux
