### ISSUE TITLE
'White Screen' chat window issue if Zoom not 1.0

### ISSUE THREAD

**Issue by emulti** [deltachat/deltachat-desktop#1526] opened 2020-03-31 13:06 UTC
![dc whitescreen](https://user-images.githubusercontent.com/7505390/78030358-dc170080-7359-11ea-8458-aecf58eb1e80.png)
- Platform (linux/mac/windows): Arch Linux
- Delta Chat Desktop Version: 1.2.0 (reported by app)  from AUR deltachat-desktop-git r1.1.0.r1.g8602c727-1
- Expected behavior: Deltachat displays normally
- Actual behavior: White Screen except for menu bar
- Steps to reproduce the problem:

Noticed this 'white screen' issue after starting to use the 'zoom' option to reduce the text size. I used Zoom 0.8. 
When in a chat, action in the UI such as using backspace key to correct previously-typed text before sending seems to trigger a 'white screen' where the content of the entire chat window disappears. Not every time, however, just occasionally. Sometimes just typing a message before sending can trigger the issue.
After that, re-launch of DC always produces a white chat window after the initial 'select a chat or create a new chat' appears, presumably when moving to the chat that was last used. Menus still operate.
However, unless the 'zoom' setting is changed back to 1.0, the white screen is permanent on every launch.
After changing back to zoom 1.0 via menus and relaunch, the problem disappears.
Have not been able to reproduce the issue with zoom set to 1.0, so that's a workaround for now.

**Comment by Simon-Laux** [comment] 2020-03-31 17:19
Could you send us the logfile?
I can't image that the zoomlevel is related to this, this seems unlikely to me.

**Comment by emulti** [comment] 2020-04-01 21:12
Sorry for the delay- yes 'correlation does not imply cause'. 

But I can confirm that setting zoom back  to 1.0 restores normal operation, and the issue only appeared when zoom was set to 0.8

With zoom set to 0.8, typing a message (a full sentence not just a few characters as in initial testing) and the screen went blank.

It is reproducible: 

Set zoom to 0.8, restart deltachat. 
Select session used for testing to an alternate email I have. 

Start typing message to contact:
"Now is the time for all good men to come to the aid of the party"
The screen goes white at a variable point 20-30 characters into the sentence.

Log: see attached file. I have replaced personal identifying information. 
Sorry, it's very verbose with --log-debug

Restart with zoom=0.8 still gives white screen.

Reset zoom to 1.0 using menus and restart restores normal display.
[dclogs-whitescreen.log](https://github.com/deltachat/deltachat-desktop/files/4417687/dclogs-whitescreen.log)

Start typing message to contact:
"Now is the time for all good men to come to the aid of the party"
Message displays normally while typing and is sent.

Strange!

**Comment by gerryfrancis** [comment] 2020-04-02 16:30
@emulti Ahahaa, that's a good one, great!! I have been able to reproduce it by reducing the width of the main window after typing the sentence!

**Comment by gerryfrancis** [comment] 2020-04-02 16:44
It has something to do with the line break of the message bar.

**Comment by Simon-Laux** [comment] 2020-05-11 18:56
was fixed by #1544

**Comment by therealmaxmoon** [comment] 2020-05-15 22:29
Can someone tell me in which version it was fixed? I had exactly the same issue, because of highdpi on Linux. So I had 0.8 set. But out of the nowhere the screen went full white while typing a message in DeltaChat. After changing the setting back to 1 and restarting DeltaChat, everything was normal again.

I am using DeltaChat from [Flathub](https://flathub.org/apps/details/chat.delta.desktop) (Version 1.3.1)

**Comment by Simon-Laux** [comment] 2020-05-16 03:04
So this appears again?

**Comment by gerryfrancis** [comment] 2020-05-16 06:58
I cannot reproduce this issue anymore with version 1.3.3.

**Comment by therealmaxmoon** [comment] 2020-05-16 07:40
> So this appears again? Can you check your dev console under `View->Developer-Developer Tools` and sent me a screenshot of last console messages there after the white-screen occurred?

![deltachat_error](https://user-images.githubusercontent.com/18206603/82112838-383eb400-9751-11ea-99cf-d5119f714439.png)

I don't know if I am a good example, because I am using Flatpak. This could be an issue too.

**Comment by Jikstra** [comment] 2020-05-16 11:11
We should aim for pure css zoom levels, this electron thing is basically a hack that breaks many things (like the composer which we had to fix in a not sooo nice way)

**Comment by Simon-Laux** [comment] 2020-10-13 17:09
please reopen this issue when it re-apears

**Closed by Simon-Laux** 2020-10-13 17:09 UTC
Labels: bug
