### ISSUE TITLE
right-clicking an enlarged image does "select all"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2217] opened 2021-04-11 16:00 UTC
when opening an image in the gallery and right-click that image it "select all" is done before the context menu is shown. this led to a weird completely blue screen:

<img width=500  src=https://user-images.githubusercontent.com/9800740/114311579-a3267580-9aef-11eb-9da4-7009f1bd08b1.png>

expected behavior would be to show only the context menu (which should also contain "export attachment" btw, but that is another issue)

**Comment by Simon-Laux** [comment] 2022-03-12 19:22
does this still appear? what are the steps to reproduce it?

**Comment by Simon-Laux** [comment] 2022-03-12 20:32
can't reproduce it, so closing now

**Closed by Simon-Laux** 2022-03-12 20:32 UTC
Labels: bug

**Comment by r10s** [comment] 2022-03-14 12:07
yip, i can confirm, this is fixed somehow by the latest release. maybe by the previous/next additions or so.

autofix :)
