### ISSUE TITLE
first send email from desktop-client to native-email unencrypted

### ISSUE THREAD

**Issue by viisauksena** [deltachat/deltachat-desktop#423] opened 2018-12-12 21:41 UTC
- Platform (linux/mac/windows): debian stretch
- Delta Chat Desktop Version: debian - v0.90.1
- Expected behavior: first email encrypted,or strong sign that this first email is unencrypted
- Actual behavior: first email to a not yet known email is unencrypted
- Steps to reproduce the problem: just send to a not yet known email
- Screenshots: none
- Logs:none

**Comment by r10s** [comment] 2018-12-12 22:12
hi @viisauksena, thank you for your post.

you're right, the first message is not encrypted by [Autocrypt](https://autocrypt.org/) (Autocrypt is used by Delta Chat by default).

Autocrypt wants to protect against mass surveillance while keeping things for the user as simple as possible - the encryption should not stay in the way of communication - otherwise it won't be widely adapted - see gpg & co.

however,  Autocrypt does not aims to be a replacement for pgp/gpg - it wants to be a replacement for _clear text mails_.

but, of course, we know that there are users that require a higher level of security. Delta Chat offers so called _verified groups_ for this purpose. While still being in development, they will offer an even higher level of security as they not only encrypt by default but also allow a very simple out-of-band-verification flow.

**Comment by ralphtheninja** [comment] 2018-12-12 22:56
Since this is by design, closing.

**Closed by ralphtheninja** 2018-12-12 22:56 UTC

**Comment by karissa** [comment] 2018-12-12 23:00
I do think it's important and perhaps would be nice to think about this for both android and desktop -- could be a suggested 'first message' that is sent during the contact request process 'Hi, let's start an encrypted chat, just reply here.' or something of that nature.

**Comment by r10s** [comment] 2018-12-12 23:54
yeah, sth. like that is possible.
maybe even more autocrypt-related.
we could file an issue in the interface repo or in the forum. not sure what the correct place for this is :)

**Comment by viisauksena** [comment] 2018-12-13 00:08
> Since this is by design, closing.

*wtf - delta.chat is promoted heavily with end2end encryption - and even if the device know the public key in the agent (but not the desktop-app) - first email is send unencrypted without a hint - and this is in your words "is broken by design"

**Comment by hpk42** [comment] 2018-12-13 10:12
On Wed, Dec 12, 2018 at 16:08 -0800, viisauksena wrote:
> > Since this is by design, closing.
> 
> *wtf - delta.chat is promoted heavily with end2end encryption - and even if the device know the public key in the agent (but not the desktop-app) - first email is send unencrypted without a hint - and this is in your words "is broken by design" 

I think a hint would be useful indeed. Currently it says in a grey box: 

Send message to XXX:
- It is okay if XXX does not use Delta Chat.
- Delivering the first message may take a while 

and maybe we could rather say:

- Delivering the first message may take a while 
  and is unencrypted.

?

**Comment by r10s** [comment] 2018-12-14 16:16
@hpk42 added your suggestion
