### ISSUE TITLE
Client crashes if the search is used

### ISSUE THREAD

**Issue by Luensche** [deltachat/deltachat-desktop#1803] opened 2020-07-17 09:17 UTC
- Operating System (Linux/Mac/Windows/iOS/Android): Windows
- Delta Chat Version: 1.4.3
- Expected behavior: Find a chat
- Actual behavior: Crashing
- Steps to reproduce the problem: Type something in the search (I was starting with Me..)
- Screenshots:
![grafik](https://user-images.githubusercontent.com/17471658/87770124-dec13700-c81e-11ea-9d26-fbee0bb6cf7c.png)

- Logs:

Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.xi (bundle.js:12:59823)
    at useContext (bundle.js:4:4989)
    at u (bundle.js:30:973)
    at d (bundle.js:516:1469)
    at bundle.js:946:4791
    at d.value (bundle.js:814:3053)
    at so (bundle.js:12:71404)
    at co (bundle.js:12:71199)
    at Bo (bundle.js:12:106181)
    at Qu (bundle.js:12:90967)

**Comment by gerryfrancis** [comment] 2020-07-17 09:59
@Luensche Thanks for reporting. I cannot reproduce your issue in Delta Chat for Desktop version 1.10.0. Could you please retry with this version and report back? You can get it from here: https://download.delta.chat/desktop/v1.10.0/ Many thanks in advance.

**Comment by Luensche** [comment] 2020-07-17 10:13
Is this a beta version? Because if I go to https://delta.chat/de/download and click on "Get it on Windws" I will get 1.4.3.

**Comment by Luensche** [comment] 2020-07-17 10:14
I've tested it with 1.10.0 and I won't get the ex til now.

**Comment by gerryfrancis** [comment] 2020-07-17 10:39
> Is this a beta version?

@Luensche It is a test version, not officially listed on Github, but definitely an improvement compared to version 1.4.3. ;)

> I won't get the ex til now.

@Luensche Great, thanks for reporting back, I am closing here.

**Closed by gerryfrancis** 2020-07-17 10:39 UTC
Labels: bug

**Comment by Simon-Laux** [comment] 2020-07-17 16:11
link to the fixing commit https://github.com/deltachat/deltachat-desktop/pull/1785/commits/6ce5a29178954ddda66577a620268368689b6914
