### ISSUE TITLE
Missing values for various keys

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#947] opened 2019-08-21 06:32 UTC
keys are used here:
https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/conversations/Message.js#L304
https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/conversations/MessageMetaData.js#L61
Just found some more missing labels: contactAvatarAlt, incomingError, imageFailedToLoad, videoScreenshotFailedToLoad

All these keys are camelCase instead of  snake_case...?

I see that for example imageFailedToLoad was added once: https://github.com/deltachat/deltachat-desktop/commit/1d7572fec26fa50957252eaeb3746411a7dca5ac

**Comment by Jikstra** [comment] 2019-08-21 12:00
That's all old signal code that is basically dead and was never used. We still kept those params in the components. We can remove them if we want to.

**Comment by nicodh** [comment] 2019-08-21 13:43
At least for retrySend & sendFailed (the first 2 links in issue description) I see an error message in console when there is an unsent message in chat list

**Comment by Jikstra** [comment] 2019-09-24 23:41
Duplicate of https://github.com/deltachat/deltachat-desktop/issues/838

**Closed by Jikstra** 2019-09-24 23:41 UTC
Labels: translations
