### ISSUE TITLE
"Blue dot" tray icon missing

### ISSUE THREAD

**Issue by markoong** [deltachat/deltachat-desktop#2477] opened 2021-12-20 15:53 UTC
The "blue dot" tray icon is missing.

- Operating System (Linux/Mac/Windows/iOS/Android): Linux (Flatpak)
- Delta Chat Version: 1.26.0
- Expected behavior: Blue dot shown on unread messages
- Actual behavior: "unknown" placeholder icon shown on unread messages
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by Simon-Laux** [comment] 2022-01-10 18:55
which desktop environment are you using?

**Comment by markoong** [comment] 2022-01-27 14:09
On Mon, 10 Jan 2022 10:55:39 -0800
Simon Laux ***@***.***> wrote:

> which desktop environment are you using?
> 

KDE 5.

-- 
Marco

CONFIDENTALITY NOTICE:
The information contained in this message as well as the attached
file(s) is confidential/privileged and is only intended for the person
to whom it is addressed. If the reader of this message is not the
intended recipient or the employee or agent responsible for delivering
the message to the intended recipient, or you have received this
communication in error, please be aware that any dissemination,
distribution or duplication is strictly prohibited, and can be illegal.
Please notify us immediately and delete all copies from your mailbox and
other archives. Thank you
------------------------------------------------------------------------
In ottemperanza con il nuovo Regolamento Europeo GDPR n. 679/2016, le
informazioni contenute in questo messaggio sono riservate e
confidenziali. Il loro utilizzo è consentito esclusivamente al
destinatario del messaggio, per le finalità indicate nel messaggio
stesso. Qualora Lei non fosse la persona a cui il presente messaggio è
destinato, La invitiamo ad eliminarlo dal Suo Sistema ed a distruggere
le varie copie o stampe, dandocene gentilmente comunicazione. Ogni
utilizzo improprio è contrario ai principi del nuovo Regolamento Europeo
GDPR n. 679/2016.

**Comment by Simon-Laux** [comment] 2022-04-06 20:02
works for me in gnome+flatpak, can you try the current version again? and then reopen the issue if it still persists on kde

**Comment by markoong** [comment] 2023-02-13 12:04
This is still a very annoying problem! Could you check that the file path under KDE are actually valid?

**Comment by farooqkz** [comment] 2023-07-27 13:17
I can't reproduce.

 - xUbuntu 22.04
 - i3 instead of xfwm
 - from flatpak(v1.38.1)

**Comment by Simon-Laux** [comment] 2023-07-27 14:17
it is about KDE and flatpak, I could also not reproduce it on gnome ;)

**Comment by Simon-Laux** [comment] 2024-07-31 23:21
I transferred this to flat hub dc repo manually: https://github.com/deltachat/deltachat-desktop/issues/2477

**Closed by Simon-Laux** 2024-07-31 23:21 UTC
Labels: bug, packaging, Packaging/Linux/flatpak
