### ISSUE TITLE
1.48.0 crashes sometimes when i try to quote-reply

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#4337] opened 2024-11-12 17:21 UTC
![image](https://github.com/user-attachments/assets/c471367c-fc9b-4945-80f0-d5ecb9ede6b9)

**Comment by WofWca** [comment] 2024-11-13 10:09
Is it 100% reproducible for you? I can't reproduce.

**Comment by hpk42** [comment] 2024-11-13 10:48
No, it's not reproducible.  If that rules out fixing it feel free to close. 
I'll file another issue if it reappears. Was the first itme i encountered it
(but i am also not often quote-replying to webxdc-app messages).

**Comment by WofWca** [comment] 2024-11-13 11:02
I looked through all the `.slice` we have in the codebase and narrowed it down to these two lines:

https://github.com/deltachat/deltachat-desktop/blob/78fef8b6b45329250c369dc23bd1c4bcd02adca5/packages/frontend/src/components/message/Message.tsx#L805

https://github.com/deltachat/deltachat-desktop/blob/a5c02433976909fe01a64f3049c96d0d101ae9d8/packages/frontend/src/components/Reactions/index.tsx#L35

They produce the same stack trace, unlike other `.slice`. I might have missed some, but the first line I mentioned looks like the likely candidate.

**Comment by WofWca** [comment] 2024-11-13 12:01
@Simon-Laux also encountered this issue:

> must be in react render function and inside of the message list+composer component, because that error boundary was triggered. I also can not reproduce it with the echo bot. basically I was quickly switching between quote messages while your answers came in.

And I myself also just managed to reproduce this with echo@nine.testrun.org. I sent a message to it and starting quickly pressing Ctrl+Up to quote, and got the crash: `Cannot read properties of undefined (reading 'slice')`.

And indeed it points to this line, `Message.tsx:805:28)`:

https://github.com/deltachat/deltachat-desktop/blob/78fef8b6b45329250c369dc23bd1c4bcd02adca5/packages/frontend/src/components/message/Message.tsx#L805

However, I am not 100% sure that this is the very same issue as in the original post.

**Comment by WofWca** [comment] 2024-11-13 12:46
This is what I got by putting a conditional breakpoint `quote.text == undefined` there.

![image](https://github.com/user-attachments/assets/7e4ffffd-4259-497d-852a-499916295ed1)

Looks like these two pieces of code could be causing the crash:

https://github.com/deltachat/deltachat-desktop/blob/f9362a941bc6568dce3859052b3744ab925c1a88/packages/frontend/src/components/composer/Composer.tsx#L599-L602

https://github.com/deltachat/deltachat-desktop/blob/f9362a941bc6568dce3859052b3744ab925c1a88/packages/frontend/src/components/composer/Composer.tsx#L662-L665

They actually mutate the state, `draftState`, bypassing `_setDraft`, and make it invalid (because `.quote` is missing the required properties). `draftRef` was introduced in 4bbdbe390b03e15eb059ca6af15a44156413ee44.

I think this issue should belong to the "New Composer" project, given that it is not super severe. Un-assign it from the project if you disagree.

**Closed** 2024-12-08 13:35 UTC
Labels: bug
