### ISSUE TITLE
member list incomplete in chat request

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2384] opened 2021-10-01 23:53 UTC
the member list for chat request seems to lack one contact, eg. when "3 members" are shown, the list only shows "2":

<img width=300 src=https://user-images.githubusercontent.com/9800740/135696557-72a05f83-ecba-4d23-9c35-3454fb33d3c7.png>

once the chat request is accepted, the whole list is shown:

<img width=300 src=https://user-images.githubusercontent.com/9800740/135696646-e026f78f-8976-485e-9213-e79364d1d6e8.png>

(seen on 1.22.1 on mac)

**Comment by Simon-Laux** [comment] 2021-10-02 12:26
probably duplicate of https://github.com/deltachat/deltachat-desktop/issues/1244

**Comment by Jikstra** [comment] 2021-10-13 23:52
Fixed by https://github.com/deltachat/deltachat-desktop/pull/2387

**Closed by Jikstra** 2021-10-13 23:52 UTC
Labels: bug
