### ISSUE TITLE
Alt+Shift combination causes menu to open

### ISSUE THREAD

**Issue by MRZA-MRZA** [deltachat/deltachat-desktop#709] opened 2019-03-03 19:30 UTC
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: 0.101.0
- Expected behavior: Menu shouldn't open
- Actual behavior: Menu opens
- Steps to reproduce the problem: Press Alt+Shift

When I'm typing and want to switch input language I press Alt+Shift that causes menu to open. It interrupts my input.

**Comment by Jikstra** [comment] 2019-03-04 19:59
Which menu opens? Can't reproduce on arch + kde plasma. Which desktop/window manager are you using?

**Comment by MRZA-MRZA** [comment] 2019-03-05 18:38
Application menu. I'm using Xubuntu 18.10 with XFCE.

**Comment by Jikstra** [comment] 2019-03-05 21:23
Can you test if this happens with other programs too? It's possible that this is a xfce specific thing, maybe a general gtk option. A keybinding to open the application menu.

**Comment by MRZA-MRZA** [comment] 2019-03-06 18:27
I think this should clarify everything: https://github.com/vector-im/riot-web/issues/4345

**Comment by Vftdan** [comment] 2019-03-27 20:21
I have the same problem. But I have alt+CapsLock bound as language switch: `setxkbmap -layout us,ru -option grp:alt_caps_toggle`. DeltaChat menu is triggered by alt+CapsLock, alt+Shift does nothing.
OS: Linux Mint 19 Tara
WM: bspwm

**Comment by nicodh** [comment] 2019-07-13 22:42
Should be fixed since we had an electron upgrade and bug vector-im/riot-web#4345 is fixed. I can't reproduce it on Ubuntu 18.04

**Closed by nicodh** 2019-07-13 22:42 UTC
