### ISSUE TITLE
Ubuntu 19.04: Deltachat freezes on message send

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-desktop#806] opened 2019-05-23 19:09 UTC
- Platform (linux/mac/windows): Ubuntu 19.04
- Delta Chat Desktop Version: 0.103.0
- Expected behavior: 
- Actual behavior: on sending messages load rises to 100% and DS freezes.
 the last working version was v0.101.0. since then DS freezes in any version.
- Steps to reproduce the problem: install DeltaChat-ubuntu-19_04-rpgp-0.103.0.deb
- Screenshots: 
![image](https://user-images.githubusercontent.com/37833326/58279339-65ef5800-7d9e-11e9-9876-ae4c872a37a6.png)

![image](https://user-images.githubusercontent.com/37833326/58279370-83bcbd00-7d9e-11e9-96e5-65a596d34a62.png)

**Comment by Simon-Laux** [comment] 2019-05-24 12:18
I have it freezing sometimes when many new messages are fetched and always when messages are fetched and I try to switch account #702. Those freezing issues could be related. But my cpu load didn't rise. (At the moment I use the experimental rust core and i didn't test if those issues are still there yet)

Is it recovering after the freeze? Is the message sent eventually?

**Comment by ralphtheninja** [comment] 2019-05-24 12:37
@nicodh Is this what you're experiencing on one of your macs?

**Comment by Jikstra** [comment] 2019-05-24 12:47
I have a ubuntu 19.04 vm in brombi, i'm going to start that one up and try to reproduce it. I guess this could be related to rpgp. What i can try to do is, creating a 19.04 .deb release which uses netpgp.

**Comment by g6094199** [comment] 2019-05-24 13:07
>  What i can try to do is, creating a 19.04 .deb release which uses netpgp.

would be nice for testing

**Comment by Jikstra** [comment] 2019-05-27 08:11
I just created a .deb using netpgp, haven't tested it in a vm yet. Will do so later.
@g6094199 in case you already want to test, check out:
https://github.com/deltachat/deltachat-desktop/releases/download/v0.103.0/DeltaChat-ubuntu-19_04-rpgp-0.103.0.deb

**Comment by g6094199** [comment] 2019-05-27 09:56
Hola!

I installed your "nightly" build. On my 2nd ubuntu system, where is use generally the flatpak version for testing purposes.
So install the .deb an i had to do the config process. Adding the mail account was ok, but when i try to use the autocrypt key transfer DS freezes after adding the transfer code and hitting ok. The transfer takes forever. CPU load rises to 100%.


![image](https://user-images.githubusercontent.com/37833326/58411989-d71c5d00-8075-11e9-8925-e1a09575b468.png)

I also cant just import a backup file since DS crashes instantly.  [See](https://github.com/deltachat/deltachat-desktop/issues/815#issue-448763014) :-)

**Comment by Jikstra** [comment] 2019-05-27 13:08
@g6094199 i just tested the nightly build and it's broken, it shouldn't even start. I'm currently uploading a new one which I tested in a vm. The version you're using is somehow weird because it says "rgpg_enabled=1" which should be disabled. 

New nightly build:
https://github.com/deltachat/deltachat-desktop/releases/download/v0.103.0/DeltaChat-ubuntu-19_04-netpgp-0.103.0-2.deb

**Comment by g6094199** [comment] 2019-05-27 13:34
ok.

autocrypt transfer worked this time. with the new build. 
i also can send messages now as expected. it seems to work now.

**Comment by Jikstra** [comment] 2019-05-27 16:13
Okay so this seems to be a rpgp issue. @dignifiedquire can you help out?

**Comment by dignifiedquire** [comment] 2019-05-27 16:25
not sure, there is not much to go on here, without any logs

**Comment by Jikstra** [comment] 2019-05-27 16:28
@g6094199 can you run the deltachat-desktop from the terminal? 
`LD_PRELOAD="/opt/DeltaChat/libdeltachat/lib/x86_64-linux-gnu/libdeltachat.so" /opt/DeltaChat/deltachat-desktop-electron --debug --log-debug --log-to-console` should give as much log output as possible.

**Comment by g6094199** [comment] 2019-05-27 16:59
Your netgpg version is very chatty:

`deltachat-desktop LD_PRELOAD="/opt/DeltaChat/libdeltachat/lib/x86_64-linux-gnu/libdeltachat.so" /opt/DeltaChat/deltachat-desktop-electron --debug --log-debug --log-to-console 
Logfile: /home/x/.config/DeltaChat/logs/2019-05-27T16:43:48.792Z.log
{ message:
   'Wählen Sie einen Chat aus oder erstellen Sie einen neuen Chat.' }
main/index INFO [] cwd /home/x/.config/DeltaChat
main/deltachat/login INFO [] Using deltachat instance /home/x/.config/DeltaChat/6f647973736575735f68656c645f6465725f616e74696b65407765622e6465
main/ipc DEBUG [] RENDER
main/menu INFO [] rebuilding menu with locale de
main/mainWindow INFO [] toggleDevTools
main/deltachat/login INFO [] Ready
main/deltachat/login INFO [] dc_get_info { deltachat_core_version: 'v0.43.0',
  sqlite_version: '3.27.2',
  sqlite_thread_safe: '1',
  libetpan_version: '1.8',
  openssl_version: '1.1.1b',
  rpgp_enabled: '0',
  compile_date: 'May 27 2019, 12:40:10',
  arch: '64',
  number_of_chats: '3',
  number_of_chat_messages: '48',
  messages_in_contact_requests: '0',
  number_of_contacts: '2',
  database_dir:
   '/home/x/.config/DeltaChat/6f647973736575735f68656c645f6465725f616e74696b65407765622e6465/db.sqlite',
  database_version: '55',
  blobdir:
   '/home/x/.config/DeltaChat/6f647973736575735f68656c645f6465725f616e74696b65407765622e6465/db.sqlite-blobs',
  display_name: '0',
  is_configured: '1',
  entered_account_settings: 'x@web.de 0:***:0:0 0:0:0:0 0',
  used_account_settings:
   'x@web.de x:***:imap.web.de:993 x:***:smtp.web.de:587 AUTH_NORMAL IMAP_SSL SMTP_STARTTLS',
  inbox_watch: '1',
  sentbox_watch: '1',
  mvbox_watch: '1',
  mvbox_move: '1',
  folders_configured: '3',
  configured_sentbox_folder: 'Gesendet',
  configured_mvbox_folder: 'DeltaChat',
  mdns_enabled: '0',
  e2ee_enabled: '1',
  private_key_count: '2',
  public_key_count: '3',
  fingerprint: 'AA9F9C0C81ABEA969E4C975F0E1758BFF19775DD' }
main/ipc DEBUG [] RENDER
main/deltachat DEBUG [] ALL event 100 [ 0,
  'Opened "/home/x/.config/DeltaChat/6f647973736575735f68656c645f6465725f616e74696b65407765622e6465/db.sqlite".' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'SMTP-jobs started...' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'SMTP-jobs ended.' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'SMTP-idle started...' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'INBOX-jobs started...' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'INBOX-jobs ended.' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'IMAP-server imap.web.de:993 SSL-connected.' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'IMAP-server imap.web.de:993 SSL-connected.' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'IMAP-server imap.web.de:993 SSL-connected.' ]
main/deltachat DEBUG [] ALL event 102 [ 0, 'IMAP-login as x ok.' ]
main/deltachat DEBUG [] ALL event 100 [ 0,
  'IMAP-capabilities: IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'SENTBOX-fetch started...' ]
main/deltachat DEBUG [] ALL event 102 [ 0, 'IMAP-login as xx ok.' ]
main/deltachat DEBUG [] ALL event 100 [ 0,
  'IMAP-capabilities: IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'MVBOX-fetch started...' ]
main/deltachat DEBUG [] ALL event 102 [ 0, 'IMAP-login as odysseus_held_der_antike ok.' ]
main/deltachat DEBUG [] ALL event 100 [ 0,
  'IMAP-capabilities: IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'INBOX-fetch started...' ]
main/deltachat DEBUG [] ALL event 100 [ 0, '0 mails read from "Gesendet".' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'SENTBOX-fetch done in 135 ms.' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'SENTBOX-IDLE started...' ]
main/deltachat DEBUG [] ALL event 100 [ 0, '0 mails read from "INBOX".' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'INBOX-fetch done in 118 ms.' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'INBOX-IDLE started...' ]
main/deltachat DEBUG [] ALL event 100 [ 0, '0 mails read from "DeltaChat".' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'MVBOX-fetch done in 159 ms.' ]
main/deltachat DEBUG [] ALL event 100 [ 0, 'MVBOX-IDLE started...' ]
{ message:
   'Wählen Sie einen Chat aus oder erstellen Sie einen neuen Chat.' }
init: 1702.290ms
main/state INFO [] Saving state to /home/xxx/.config/DeltaChat/config.json
main/ipc DEBUG [] RENDER
main/state INFO [] Saving state to /home/xx/.config/DeltaChat/config.json
main/state INFO [] Saving state to /home/x/.config/DeltaChat/config.json
Quitting now. Bye.
`

But the rgpg is NOT:
`deltachat-desktop LD_PRELOAD="/opt/DeltaChat/libdeltachat/lib/x86_64-linux-gnu/libdeltachat.so" /opt/DeltaChat/deltachat-desktop-electron --debug --log-debug --log-to-console
Logfile: /home/xx/.config/DeltaChat/logs/2019-05-27T16:57:28.817Z.log
{ message:
   'Wählen Sie einen Chat aus oder erstellen Sie einen neuen Chat.' }
{ message:
   'Wählen Sie einen Chat aus oder erstellen Sie einen neuen Chat.' }
init: 1342.668ms
/usr/local/bin/deltachat-desktop: Zeile 8:  7211 Getötet                LD_PRELOAD="/opt/DeltaChat/libdeltachat/lib/x86_64-linux-gnu/libdeltachat.so" /opt/DeltaChat/deltachat-desktop-electron
`

Whats wrong?

**Comment by Jikstra** [comment] 2019-05-28 12:13
Is it possible that deltachat already fetched all messages? Deltachat is quite chatty if it's fetching new messages, but if you start it again and it already fetched everything it should be fine. The most output i see on the netpgp is about fetching messages.

**Comment by g6094199** [comment] 2019-05-29 16:26
maybe it already fetched all messages, but when i send a test message not additional loging happens. it just freezes.

![image](https://user-images.githubusercontent.com/37833326/58573923-18139d80-823f-11e9-9cf9-651e7d23d32e.png)

after killing and restarting DS the messages is shown as sent AND is still in the typing field, too

**Comment by ralphtheninja** [comment] 2019-05-29 17:16
We know what this is about now and it has been fixed in rpgp https://github.com/rpgp/rpgp/commit/b9ecee8aff4f835fc0ce50e2f3fd43e28cdefce9

@Jikstra Maybe we should just make a new release of desktop based on `rpgp@0.2.1`?

**Comment by Jikstra** [comment] 2019-05-30 17:55
Making new releases is currently blocked by https://github.com/rpgp/rpgp/issues/39
All ci scripts seem to be broken currently.

**Comment by dignifiedquire** [comment] 2019-05-30 18:42
https://github.com/rpgp/rpgp/pull/40

**Comment by dignifiedquire** [comment] 2019-05-31 08:10
This PR should fix the issues

**Comment by Jikstra** [comment] 2019-05-31 13:44
@dignifiedquire shall i hardcode a specific git tag for rpgp or just use the latest master?

**Comment by dignifiedquire** [comment] 2019-05-31 15:48
@Jikstra just use the commit of current `master` for now

**Comment by Jikstra** [comment] 2019-06-09 17:29
@g6094199 i just uploaded a .deb for deltachat 0.104.0 for ubuntu 19.04 using a new rpgp version, can you try out that version?

https://github.com/deltachat/deltachat-desktop/releases/download/v0.104.0/DeltaChat-ubuntu-18_04-rpgp-0.104.0.deb

**Comment by g6094199** [comment] 2019-06-09 18:26
hola!

there was no 19.04 version. but anyway i uses the 18.10 verseion which seem to work quiet nicely on my first tests. i will have an eye on it but it seems to be fixed. 

THX!

**Closed** 2019-06-09 19:29 UTC
Labels: bug

**Comment by Jikstra** [comment] 2019-06-10 05:36
@g6094199 thanks for testing! There now should be a 19.04 release, but in general they should be quite interoperable.
