### ISSUE TITLE
First message in Chat is not visible

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#1189] opened 2019-12-07 12:44 UTC
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: 0.840.0-PREVIEW
- Expected behavior: See all messages
- Actual behavior: the first message in a chat is not visible
- Steps to reproduce the problem:

1. receive a message for a not yet existing chat (you also can delete a existing chat and then receive a first message.)
2. The chat window show nothing. 
3. receive a second message. This will be shown.

This also happens if you send a autocrypt message. The first one is not visible.

**Comment by Simon-Laux** [comment] 2019-12-07 16:15
duplicate of #1122

**Closed by Simon-Laux** 2019-12-07 16:15 UTC
Labels: duplicate
