### ISSUE TITLE
"Recently seen"-indicator does not disappear automatically after 10 minutes

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/deltachat-desktop#2966] opened 2022-10-26 11:43 UTC
"Recently seen"-indicator does not disappear automatically after 10 minutes. 
Only after restarting DeltaChat or switching to archived chats and back.

**Comment by Jikstra** [comment] 2022-10-26 12:58
Thank you :) Here the core ticket: https://github.com/deltachat/deltachat-core-rust/issues/3646

**Comment by Simon-Laux** [comment] 2022-10-26 14:23
technically this is a duplicate of #2926

**Closed as completed by Simon-Laux** 2022-10-26 14:23 UTC
Labels: bug, duplicate
