### ISSUE TITLE
Search broken: each typed char shifts focus

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#2051] opened 2021-01-13 08:41 UTC
reproduced by Ghostz and me: he on "desktop-2046", me on current master versions of everything: if you search in the chat list input field, the typing focus shifts away after each character.  It's a pretty severe regression so i am marking it as blocker.

**Comment by Jikstra** [comment] 2021-01-13 09:02
Duplicate of https://github.com/deltachat/deltachat-desktop/issues/2037 ;)

**Closed by Jikstra** 2021-01-13 09:02 UTC
Labels: blocker
