### ISSUE TITLE
ChatList Issues

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#859] opened 2019-06-13 21:30 UTC
To Fix:
- [x] Sometimes we have duplicated entries (somebody changed his setup and I had him like 4 times in the list)
- [x] Sometimes I get duplicated contact requests at random places in the List
- [x] Sometimes the archived chats button is over empty chats :bug:
- [x] Sometimes I get duplicated key warnings/errors which might be the cause of those problems

**Comment by nicodh** [comment] 2019-06-15 10:35
Can you please test https://github.com/deltachat/deltachat-desktop/pull/850 - the problems you report should be fixed there.
The duplicate key error is coming from chatList or chatView (message list)?

**Comment by Simon-Laux** [comment] 2019-06-15 16:48
I marked all still happening bugs with :bug:

**Comment by nicodh** [comment] 2019-06-15 16:49
Is there a way to reproduce it? Or does it just happens randomly...? And is it just one chat or multiple?

**Comment by Simon-Laux** [comment] 2019-06-15 16:55
Sometimes (found no way to reproduce it yet). Multiple chats are in this case under the archive button, but only chats that have no messages

**Comment by Simon-Laux** [comment] 2019-06-15 17:00
![2019-06-15_18-59](https://user-images.githubusercontent.com/18725968/59554209-b887f280-8f9f-11e9-8a9b-84f7abe311ac.png)
Reproduced it with a combination of writing/recieving messages and searching
Also the archived chats button appeared in the search results.

**Comment by Simon-Laux** [comment] 2019-06-15 17:03
I checked the other ones now, because they were likely side effects of the duplicated key problem.

**Comment by nicodh** [comment] 2019-06-15 17:13
You "could" reproduce them? So they still happen?

**Comment by Simon-Laux** [comment] 2019-06-15 17:24
sorry meant couldn't

**Comment by Simon-Laux** [comment] 2019-06-27 10:48
I get the same key error/warning again and some duplicated chatlist items:
![2019-06-27_12-47](https://user-images.githubusercontent.com/18725968/60260397-cdd31a00-98d9-11e9-9d40-9782bd890880.png)

**Comment by nicodh** [comment] 2019-06-27 11:14
Does it only happen with "empty" chats?

**Comment by nicodh** [comment] 2019-06-27 11:15
Did you find out how to reproduce it?

**Comment by Simon-Laux** [comment] 2019-06-27 11:15
thats not an empty chat - so no

**Comment by Simon-Laux** [comment] 2019-06-27 11:18
I didn't found out more than that it only happens when they're incoming messages.

**Comment by Jikstra** [comment] 2019-07-28 16:27
@Simon-Laux closing this because all open points are done. Please reopen if something is still missing.

**Closed by Jikstra** 2019-07-28 16:27 UTC
Labels: bug
