### ISSUE TITLE
Crash after click on "Contact requests"

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#755] opened 2019-04-06 10:50 UTC
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: 0.102.0-preview
- Expected behavior: open contact request window
- Actual behavior: DC immediately crashed
- Steps to reproduce the problem: Click on "Contact request" in the 3 dot menue

**Comment by Simon-Laux** [comment] 2019-04-06 20:01
possibly duplicate of #737

**Comment by Simon-Laux** [comment] 2019-04-07 14:18
@webratte does it also happen on the current master?

**Comment by webratte** [comment] 2019-04-07 14:30
I don't know.
I'm not able to compile it.
I only can test already compiled versions.

I hope I have used the right terms ;-)

**Comment by Simon-Laux** [comment] 2019-04-07 16:54
Then I would say we close this issue and you reopen it when it still happens in the next version. 

Am 7. April 2019 16:30:40 MESZ schrieb webratte <notifications@github.com>:

**Comment by webratte** [comment] 2019-04-07 17:03
Yes, I will report if I have tested the next release.

**Closed** 2019-04-07 17:10 UTC
Labels: bug
