### ISSUE TITLE
image message bubbles cropped on small window widths

### ISSUE THREAD

**Issue by violoncelloCH** [deltachat/deltachat-desktop#579] opened 2019-01-10 23:06 UTC
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 0.98.1
- Expected behavior: message bubbles with images should be fully shown regardless the width of the window
- Actual behavior: message bubbles with images are cropped it the window is too small
- Steps to reproduce the problem: send an Image (on delta android) and resize the window to small widths
- Screenshots: 
![image](https://user-images.githubusercontent.com/22591354/51002748-92fc4600-1534-11e9-97c4-8b32396849d1.png)
![image](https://user-images.githubusercontent.com/22591354/51002765-a3acbc00-1534-11e9-8cf0-5d8de1a60192.png)

**Comment by violoncelloCH** [comment] 2019-01-11 21:09
just remarked, that it get's horizontally scrollable in these cases...

**Comment by Jikstra** [comment] 2019-05-27 15:53
Can't reproduce, i think it should be fixed.

**Closed by Jikstra** 2019-05-27 15:53 UTC
Labels: bug, ui/ux
