### ISSUE TITLE
 sound file stays in pending

### ISSUE THREAD

**Issue by vbeh** [deltachat/deltachat-desktop#1547] opened 2020-04-09 08:23 UTC
hi
when i send a sound file or video ~4mb or larger it stays in encrypted/pending. i tried different mails(yandex,gmail) with no success. its worth mentioning that all other massages(text or photo) are being delivered with no problem.  

- Platform : Linux Mint 19.3 (i have the same problem in android 
- Delta Chat Desktop Version: 1.2 (also tried 1.1.1)
- Expected behavior: the massage has been sent :)
- Actual behavior: pending for ever
- Steps to reproduce the problem: send a music file larger than ~5mb
edit: Android problem is solved (version 1.8.1)
edit: Delta Chat Desktop Version 1.4.2 still has the problem(Linuxmint 19.3)

**Comment by gerryfrancis** [comment] 2020-04-09 18:58
@vbeh To rule out a possible issue with your mail provider, please check with another mailer. Thanks in advance.

**Comment by vbeh** [comment] 2020-04-10 06:46
@gerryfrancis thank you for your reply.
as i mentioned i did try gmail and Yandex (and now Disroot)...no difference.

**Comment by Simon-Laux** [comment] 2020-06-28 05:54
@vbeh can you send 5mb mails over those providers with other email clients such as thunderbird?

**Comment by vbeh** [comment] 2020-06-28 05:59
thank you 
good point! yes i can send ~20 mb files using Thunderbird

**Comment by gerryfrancis** [comment] 2020-06-28 06:44
> i can send ~20 mb files using Thunderbird

@vbeh Encrypted or not?

**Comment by vbeh** [comment] 2020-06-28 09:38
@gerryfrancis  not encrypted

**Comment by gerryfrancis** [comment] 2020-06-28 10:03
@vbeh And in Delta Chat?

**Comment by Simon-Laux** [comment] 2020-06-28 14:09
we have a new upcoming version that you may try https://download.delta.chat/desktop/v1.4.2/
also if the new version doesn't fix it you can disable encryption in delta-chat to check whether there is a problem with encryption of bigger files.

**Comment by vbeh** [comment] 2020-06-28 15:07
@Simon-Laux  thank you for the reply
Deltachat 1.8.1 on Android  is working fine. i just sent a 10mb video with my phone and received it on the laptop(encrypted). but the new desktop version (1.4.2 - linux) still has the problem.
disabling encryption also didn't solve the problem.

**Comment by gerryfrancis** [comment] 2020-06-28 18:06
I tried to send a ZIP file (size ~6 MB, no encryption) from Posteo to GMX, and guess what: Delta Chat crashed.

Name der fehlerhaften Anwendung: DeltaChat.exe, Version: 1.4.2.0, Zeitstempel: 0x5e574cd0
Name des fehlerhaften Moduls: DeltaChat.exe, Version: 1.4.2.0, Zeitstempel: 0x5e574cd0
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0000000004c8c2b1
ID des fehlerhaften Prozesses: 0x2b5c
Startzeit der fehlerhaften Anwendung: 0x01d64d75855c59bb
Pfad der fehlerhaften Anwendung: C:\Users\PC_USER\AppData\Local\Programs\deltachat-desktop\DeltaChat.exe
Pfad des fehlerhaften Moduls: C:\Users\PC_USER\AppData\Local\Programs\deltachat-desktop\DeltaChat.exe
Berichtskennung: f787dac5-b968-11ea-8386-d4c9eff87512
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

The last line in the log is:

`2020-06-28T17:58:27.229Z	core/event            	WARNING		"DC_EVENT_WARNING"	0	"src\\job.rs:252: SMTP failed to send: io: future timed out"`

**Comment by gerryfrancis** [comment] 2020-07-02 13:16
The crash occurs in version 1.4.3, too.

**Comment by gerryfrancis** [comment] 2020-07-16 10:51
I have performed the same test in the latest version 1.10.0, the crash does not occur anymore. @vbeh Could you update and verify, please? Thanks in advance.

**Comment by vbeh** [comment] 2020-07-16 15:49
@gerryfrancis thank you
my problem was "pending forever"  and still (in version 1.10.0)when i send a file ~4mb or larger it stays in encrypted/pending ( i can receive large files that i send with my Android phone(same internet connection- same email provider) 
why the 1.10 is so slow?

**Comment by Simon-Laux** [comment] 2020-07-16 16:41
> why the 1.10 is so slow?

not sure what you mean by that, please elaborate.(tell me more about this)

**Comment by vbeh** [comment] 2020-07-16 17:31
not related to this bug but "Deltachat 1.10.0 Linux version" has lags while adding new email/password (when I'm adding the username/password for my own account it takes 5 seconds for each letter to appear while typing) but after login its OK.

**Comment by gerryfrancis** [comment] 2020-07-16 18:45
@vbeh Please have a look at https://github.com/deltachat/deltachat-desktop/issues/1767 , it seems you have experienced the same behavior.

**Comment by vbeh** [comment] 2020-10-19 19:27
i just installed  the Flathub Deltachat (1.13.1) and the problem is solved in this version.

**Comment by vbeh** [comment] 2020-10-19 19:29
i should also try the last .deb version....the Flathub version was 1.5GB  to download and used  ~3GB disk space...

**Comment by Simon-Laux** [comment] 2021-03-22 21:41
> i just installed the Flathub Deltachat (1.13.1) and the problem is solved in this version.

looks like it was a core bug, then.
I'm closing the issue as I can't reproduce it on 1.15.3 and it's solved for you.

**Closed by Simon-Laux** 2021-03-22 21:41 UTC
Labels: bug
