### ISSUE TITLE
Windows client crashes on dragging in file

### ISSUE THREAD

**Issue by vweevers** [deltachat/deltachat-desktop#878] opened 2019-06-29 11:26 UTC
- Platform: Windows
- Delta Chat Desktop Version: 0.105.0-pre1-PREVIEW
- Actual behavior: the app froze for a few seconds, then exited
- Steps to reproduce the problem: drag a `.webm` file (or perhaps any video type, I didn't try any other yet) from your desktop / file explorer into DeltaChat
- Logs: none (no logs were written pertaining to the crash)

DC Info:

<details><summary>Click to expand</summary>

```json
{
    "arch": "64",
    "blobdir": ..,
    "compile_date": "Apr 26 2019, 00:51:50",
    "configured_mvbox_folder": "<unset>",
    "configured_sentbox_folder": "<unset>",
    "database_dir": ..,
    "database_version": "55",
    "deltachat_core_version": "v1.0.0-alpha.0",
    "display_name": ..,
    "e2ee_enabled": "1",
    "entered_account_settings": ..,
    "fingerprint": ..,
    "folders_configured": "3",
    "inbox_watch": "1",
    "is_configured": "1",
    "level": "awesome",
    "mdns_enabled": "0",
    "messages_in_contact_requests": "0",
    "mvbox_move": "1",
    "mvbox_watch": "1",
    "number_of_chat_messages": "20",
    "number_of_chats": "1",
    "number_of_contacts": "1",
    "private_key_count": "1",
    "public_key_count": "2",
    "sentbox_watch": "1",
    "sqlite_thread_safe": "1",
    "sqlite_version": "3.27.2",
    "used_account_settings": ..
}
```

</details>

---

Side-note: it's also a bit painful that I couldn't select+copy the version number in the about dialog:

![image](https://user-images.githubusercontent.com/3055345/60383383-1ae8f480-9a70-11e9-8dc4-c97856cd53ac.png)

**Comment by Simon-Laux** [comment] 2019-06-29 13:22
does it happen with other files too?

**Comment by vweevers** [comment] 2019-06-29 13:42
Reproduced with an mp4 file as well.

**Comment by Simon-Laux** [comment] 2019-06-29 14:28
I confirm - any file of any filetype that is dragged in crashes on windows

**Comment by Simon-Laux** [comment] 2019-06-29 14:35
I think it's an permissions thing -  because I can drag stuff in from the deltachat folder

**Comment by vweevers** [comment] 2019-06-29 14:58
> I think it's an permissions thing

FWIW, for me it happens randomly, not tied to a particular file, file size or file type.

**Comment by hpk42** [comment] 2019-09-30 11:02
might be fixed with core -- can someone retry? probably requires a dev-setup where you can use latest rust-core?

**Comment by hpk42** [comment] 2019-11-04 12:13
Got a report that Drag/Drop into the Windows Desktop (dev version) works now.

**Comment by MIntrovrt** [comment] 2019-11-04 18:30
Can still reproduce..  :/ any filetype crashed it once a **second** file was send

**Comment by le-mon** [comment] 2020-01-09 18:00
Tried to send some pics (from 4 to 12MB) and it crashes while trying to send. 

Version 0.901.0-PREVIEW on Windows 10

**Comment by Jikstra** [comment] 2020-01-14 02:36
Can't reproduce on windows 10 with latest master

**Comment by vweevers** [comment] 2020-01-14 08:10
I can't, short on time. I'm unsubscribing too. Good luck ❤️

**Comment by MIntrovrt** [comment] 2020-01-14 20:10
I just tried it. Seems to have been fixed.
Feel free to reopen with a more detailed description of the issue if you can still reproduce with the build given above.

**Closed by MIntrovrt** 2020-01-14 20:10 UTC
Labels: bug, needs feedback, windows
