### ISSUE TITLE
Weird emoticon view

### ISSUE THREAD

**Issue by Septias** [deltachat/deltachat-desktop#4436] opened 2024-12-23 13:14 UTC
This instance of multiple reacts in two rows looks a bit weird to me, maybe it is intended though.

![image](https://github.com/user-attachments/assets/378ec0e4-b463-46c9-a377-27c957cceb5c)

**Comment by Simon-Laux** [comment] 2024-12-23 15:06
duplicate of #4322

**Closed by Simon-Laux** 2024-12-23 15:06 UTC
Labels: bug, ui/ux
