### ISSUE TITLE
There is no app icon for i3wm/i3-gaps (i3blocks) 

### ISSUE THREAD

**Issue by kinshakov** [deltachat/deltachat-desktop#1692] opened 2020-05-30 15:16 UTC
- Operating System (Linux/Mac/Windows/iOS/Android): Arch Linux
- Delta Chat Version: Latest. Installed from aur git.
- Expected behavior: Showing icon on the pannel i3blocks, as doing other apps, for example Telegram on the screenshot below.
- Actual behavior: No any icon
- Screenshots:
![18h_15m_42s_30_May_2020](https://user-images.githubusercontent.com/13570880/83332037-9e731d00-a2a1-11ea-8697-34173301cebc.png)

- Logs:

**Comment by Simon-Laux** [comment] 2020-05-30 17:31
do you mean an tray icon with a menu?

**Comment by uglynakedguy** [comment] 2020-05-30 17:43
Yep. :) Tray icon.

**Comment by Simon-Laux** [comment] 2020-05-30 17:49
Then this is a feature request not a bug.
And a duplicate of #445.
I tried adding an electron tray icon, but it was really buggy in our currently used electron version.

**Closed** 2020-11-24 16:44 UTC
Labels: duplicate, enhancement
