### ISSUE TITLE
Feature Request: Darkmode on Desktop Client

### ISSUE THREAD

**Issue by zem** [deltachat/deltachat-desktop#899] opened 2019-07-20 15:23 UTC
as it is implemented on android.... (see picture)

![Screenshot_20190720-171658_Delta_Chat](https://user-images.githubusercontent.com/197972/61580471-dacade00-ab12-11e9-9122-e64d57682621.png)

I am propably to dumb to find that button.

**Comment by Simon-Laux** [comment] 2019-07-20 19:50
Duplicate of #457

**Closed by Simon-Laux** 2019-07-20 19:50 UTC
