### ISSUE TITLE
'new contact' in search result does not work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1818] opened 2020-07-28 00:15 UTC
when typing in a search query that does not result in a contact *and* in no matching chat , the option "New contact" is offered in the search result view.`

however, this item does not work, nothing happens when clicking on it.

i suggest to remove the item completely (as if when there is no contact match *but* a chat match) (if some quick-add shall be offered, i think "New chat" makes much more sense as "New contact" - however, just showing _no_ item is fine anyway)

**Comment by Simon-Laux** [comment] 2020-07-28 00:19
duplicate of https://github.com/deltachat/deltachat-desktop/issues/1804

**Closed** 2020-07-28 00:19 UTC
Labels: bug, duplicate
