### ISSUE TITLE
Problem with changing group name and rust-core

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#807] opened 2019-05-24 15:36 UTC
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: `refactoring-chatview` branch
- Expected behavior: group name is changed
- Actual behavior: group name is reported changed and then changed back + not decryptable message
- Steps to reproduce the problem: try changing group name using rust-core
- Screenshots:

![group-name-change](https://user-images.githubusercontent.com/308049/58339685-66ddc380-7e4a-11e9-8c40-6b22a648bb73.jpg)

**Comment by nicodh** [comment] 2019-07-04 22:49
Can't reproduce this. Maybe it's obsolete?

**Comment by ralphtheninja** [comment] 2019-07-04 23:45
Can't reproduce, but just noticed a lot of other issues when renaming groups. Should I make a new issue instead?

**Comment by hpk42** [comment] 2019-07-05 09:41
On Thu, Jul 04, 2019 at 16:45 -0700, Lars-Magnus Skog wrote:
> Can't reproduce, but just noticed a lot of other issues when renaming groups. Should I make a new issue instead?

yes -- and close this one ;)

**Closed** 2019-07-05 10:37 UTC
Labels: bug, rust-core
